awk '{ sub("\r$", ""); print }' app/code/core/Mage/Admin/etc/config.xml > app/code/core/Mage/Admin/etc/config.xml.bak;
mv app/code/core/Mage/Admin/etc/config.xml.bak app/code/core/Mage/Admin/etc/config.xml;
awk '{ sub("\r$", ""); print }' app/code/core/Mage/Adminhtml/etc/adminhtml.xml > app/code/core/Mage/Adminhtml/etc/adminhtml.xml.bak;
mv app/code/core/Mage/Adminhtml/etc/adminhtml.xml.bak app/code/core/Mage/Adminhtml/etc/adminhtml.xml;
awk '{ sub("\r$", ""); print }' app/code/core/Mage/Catalog/Model/Product/Option/Type/File.php > app/code/core/Mage/Catalog/Model/Product/Option/Type/File.php.bak;
mv app/code/core/Mage/Catalog/Model/Product/Option/Type/File.php.bak app/code/core/Mage/Catalog/Model/Product/Option/Type/File.php;
awk '{ sub("\r$", ""); print }' app/code/core/Mage/Core/Model/Email/Template/Filter.php > app/code/core/Mage/Core/Model/Email/Template/Filter.php.bak;
mv app/code/core/Mage/Core/Model/Email/Template/Filter.php.bak app/code/core/Mage/Core/Model/Email/Template/Filter.php;
awk '{ sub("\r$", ""); print }' app/code/core/Mage/Core/Model/Resource/Setup.php > app/code/core/Mage/Core/Model/Resource/Setup.php.bak;
mv app/code/core/Mage/Core/Model/Resource/Setup.php.bak app/code/core/Mage/Core/Model/Resource/Setup.php;
awk '{ sub("\r$", ""); print }' app/code/core/Mage/Core/etc/config.xml > app/code/core/Mage/Core/etc/config.xml.bak;
mv app/code/core/Mage/Core/etc/config.xml.bak app/code/core/Mage/Core/etc/config.xml;
awk '{ sub("\r$", ""); print }' app/code/core/Mage/Core/etc/system.xml > app/code/core/Mage/Core/etc/system.xml.bak;
mv app/code/core/Mage/Core/etc/system.xml.bak app/code/core/Mage/Core/etc/system.xml;
awk '{ sub("\r$", ""); print }' app/code/core/Mage/Customer/Block/Account/Resetpassword.php > app/code/core/Mage/Customer/Block/Account/Resetpassword.php.bak;
mv app/code/core/Mage/Customer/Block/Account/Resetpassword.php.bak app/code/core/Mage/Customer/Block/Account/Resetpassword.php;
awk '{ sub("\r$", ""); print }' app/code/core/Mage/Customer/controllers/AccountController.php > app/code/core/Mage/Customer/controllers/AccountController.php.bak;
mv app/code/core/Mage/Customer/controllers/AccountController.php.bak app/code/core/Mage/Customer/controllers/AccountController.php;
awk '{ sub("\r$", ""); print }' app/code/core/Mage/Downloadable/Model/Product/Type.php > app/code/core/Mage/Downloadable/Model/Product/Type.php.bak;
mv app/code/core/Mage/Downloadable/Model/Product/Type.php.bak app/code/core/Mage/Downloadable/Model/Product/Type.php;
awk '{ sub("\r$", ""); print }' app/code/core/Mage/Eav/Model/Resource/Attribute/Collection.php > app/code/core/Mage/Eav/Model/Resource/Attribute/Collection.php.bak;
mv app/code/core/Mage/Eav/Model/Resource/Attribute/Collection.php.bak app/code/core/Mage/Eav/Model/Resource/Attribute/Collection.php;
awk '{ sub("\r$", ""); print }' app/code/core/Mage/Sales/Model/Resource/Order/Item/Collection.php > app/code/core/Mage/Sales/Model/Resource/Order/Item/Collection.php.bak;
mv app/code/core/Mage/Sales/Model/Resource/Order/Item/Collection.php.bak app/code/core/Mage/Sales/Model/Resource/Order/Item/Collection.php;
awk '{ sub("\r$", ""); print }' app/code/core/Mage/Sales/controllers/DownloadController.php > app/code/core/Mage/Sales/controllers/DownloadController.php.bak;
mv app/code/core/Mage/Sales/controllers/DownloadController.php.bak app/code/core/Mage/Sales/controllers/DownloadController.php;
awk '{ sub("\r$", ""); print }' app/code/core/Mage/SalesRule/Model/Resource/Coupon/Collection.php > app/code/core/Mage/SalesRule/Model/Resource/Coupon/Collection.php.bak;
mv app/code/core/Mage/SalesRule/Model/Resource/Coupon/Collection.php.bak app/code/core/Mage/SalesRule/Model/Resource/Coupon/Collection.php;
awk '{ sub("\r$", ""); print }' app/code/core/Zend/XmlRpc/Request.php > app/code/core/Zend/XmlRpc/Request.php.bak;
mv app/code/core/Zend/XmlRpc/Request.php.bak app/code/core/Zend/XmlRpc/Request.php;
awk '{ sub("\r$", ""); print }' app/code/core/Zend/XmlRpc/Response.php > app/code/core/Zend/XmlRpc/Response.php.bak;
mv app/code/core/Zend/XmlRpc/Response.php.bak app/code/core/Zend/XmlRpc/Response.php;
awk '{ sub("\r$", ""); print }' app/design/adminhtml/default/default/layout/admin.xml > app/design/adminhtml/default/default/layout/admin.xml.bak;
mv app/design/adminhtml/default/default/layout/admin.xml.bak app/design/adminhtml/default/default/layout/admin.xml;
awk '{ sub("\r$", ""); print }' app/design/frontend/base/default/layout/customer.xml > app/design/frontend/base/default/layout/customer.xml.bak;
mv app/design/frontend/base/default/layout/customer.xml.bak app/design/frontend/base/default/layout/customer.xml;
awk '{ sub("\r$", ""); print }' app/design/frontend/base/default/template/customer/form/register.phtml > app/design/frontend/base/default/template/customer/form/register.phtml.bak;
mv app/design/frontend/base/default/template/customer/form/register.phtml.bak app/design/frontend/base/default/template/customer/form/register.phtml;
awk '{ sub("\r$", ""); print }' app/design/frontend/base/default/template/customer/form/resetforgottenpassword.phtml > app/design/frontend/base/default/template/customer/form/resetforgottenpassword.phtml.bak;
mv app/design/frontend/base/default/template/customer/form/resetforgottenpassword.phtml.bak app/design/frontend/base/default/template/customer/form/resetforgottenpassword.phtml;
awk '{ sub("\r$", ""); print }' app/design/frontend/base/default/template/page/js/cookie.phtml > app/design/frontend/base/default/template/page/js/cookie.phtml.bak;
mv app/design/frontend/base/default/template/page/js/cookie.phtml.bak app/design/frontend/base/default/template/page/js/cookie.phtml;
awk '{ sub("\r$", ""); print }' app/design/frontend/base/default/template/persistent/customer/form/register.phtml > app/design/frontend/base/default/template/persistent/customer/form/register.phtml.bak;
mv app/design/frontend/base/default/template/persistent/customer/form/register.phtml.bak app/design/frontend/base/default/template/persistent/customer/form/register.phtml;
awk '{ sub("\r$", ""); print }' app/design/frontend/default/iphone/layout/customer.xml > app/design/frontend/default/iphone/layout/customer.xml.bak;
mv app/design/frontend/default/iphone/layout/customer.xml.bak app/design/frontend/default/iphone/layout/customer.xml;
awk '{ sub("\r$", ""); print }' app/design/frontend/default/modern/layout/customer.xml > app/design/frontend/default/modern/layout/customer.xml.bak;
mv app/design/frontend/default/modern/layout/customer.xml.bak app/design/frontend/default/modern/layout/customer.xml;
awk '{ sub("\r$", ""); print }' app/design/frontend/rwd/default/layout/customer.xml > app/design/frontend/rwd/default/layout/customer.xml.bak;
mv app/design/frontend/rwd/default/layout/customer.xml.bak app/design/frontend/rwd/default/layout/customer.xml;
awk '{ sub("\r$", ""); print }' app/design/frontend/rwd/default/template/customer/form/resetforgottenpassword.phtml > app/design/frontend/rwd/default/template/customer/form/resetforgottenpassword.phtml.bak;
mv app/design/frontend/rwd/default/template/customer/form/resetforgottenpassword.phtml.bak app/design/frontend/rwd/default/template/customer/form/resetforgottenpassword.phtml;
awk '{ sub("\r$", ""); print }' app/design/frontend/rwd/default/template/persistent/customer/form/register.phtml > app/design/frontend/rwd/default/template/persistent/customer/form/register.phtml.bak;
mv app/design/frontend/rwd/default/template/persistent/customer/form/register.phtml.bak app/design/frontend/rwd/default/template/persistent/customer/form/register.phtml;
awk '{ sub("\r$", ""); print }' lib/Varien/Data/Collection/Db.php > lib/Varien/Data/Collection/Db.php.bak;
mv lib/Varien/Data/Collection/Db.php.bak lib/Varien/Data/Collection/Db.php;
awk '{ sub("\r$", ""); print }' lib/Zend/Xml/Security.php > lib/Zend/Xml/Security.php.bak;
mv lib/Zend/Xml/Security.php.bak lib/Zend/Xml/Security.php;
