<div class="myshoppage">
  <div class="container shop-steps-three">
    <div class="row">
      <div class="col-md-4 step-top step-active">
        <div class="clearfix bDiv">
          <div class="col-md-10 p0 bDivCont"> <img src="<?PHP echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/base/default/packer/images/choose a diamond.png" />
            <div class="col-md-3 p0 text-center step-number">
              <h1>1</h1>
            </div>
            <div class="col-md-9 p0 step-text"> Choose a
              <h2>diamond</h2>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4 step-top">
        <div class="clearfix bDiv">
          <div class="col-md-10 p0 bDivCont"> <img src="<?PHP echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/base/default/packer/images/choose a setting.png" />
            <div class="col-md-3 p0 text-center step-number">
              <h1>2</h1>
            </div>
            <div class="col-md-9 p0 step-text"> Choose a
              <h2>Setting</h2>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4 step-top">
        <div class="clearfix bDiv">
          <div class="col-md-10 p0 bDivCont"> <img src="<?PHP echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/base/default/packer/images/complete shopping cart.png" />
            <div class="col-md-3 p0 text-center step-number">
              <h1>3</h1>
            </div>
            <div class="col-md-9 p0 step-text"> Complete
              <h2>Shopping Cart</h2>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="filter_area clearfix">
    <div class="filter_area_title">
      <div class="container">
        <h1>create your own RING</h1>
      </div>
    </div>
    
    <?PHP 

	error_reporting(E_ALL);
	ini_set('display_errors','on');
	/* Attribute code */
	$clr = array();
	$clr['AS'] = 'asscher';
	$clr['CU'] = 'cushion';
	$clr['EC'] = 'emerald';
	$clr['HS'] = 'heart';
	$clr['MQ'] = 'marquise';
	$clr['OV'] = 'oval';
	$clr['PR'] = 'pear';
	$clr['PS'] = 'princess';
	$clr['RA'] = 'radiant';
	$clr['RD'] = 'round';
	
	$lblVals = array();
	$lblVals['EP'] = 'Extremely Poor';
	$lblVals['VP'] = 'Very Poor';
	$lblVals['PO'] = 'Poor';
	$lblVals['FR'] = 'Fair';
	$lblVals['GD'] = 'Good';
	$lblVals['VG'] = 'Very Good';
	$lblVals['EX'] = 'Excellent';
	$lblVals['H&A'] = 'Signature Ideal';
	
	
	$prods = Mage::getSingleton('catalog/layer')->setCurrentCategory(Mage::registry('current_category'))
			->getProductCollection();

	$_prodscarats = $_prodscut = array();
	foreach ($prods as $_prods){
		if($_prods->getResource()->getAttribute('d_carat')->getFrontend()->getValue($_prods) != ''){
			$_prodscarats[] = $_prods->getResource()->getAttribute('d_carat')->getFrontend()->getValue($_prods);
		}
		if($_prods->getResource()->getAttribute('d_cut')->getFrontend()->getValue($_prods) != ''){
			$_prodscut[] = $_prods->getResource()->getAttribute('d_cut')->getFrontend()->getValue($_prods);
		}
		if($_prods->getResource()->getAttribute('d_depth')->getFrontend()->getValue($_prods) != ''){
			$_prodsdepth[] = $_prods->getResource()->getAttribute('d_depth')->getFrontend()->getValue($_prods);
		}
		if($_prods->getResource()->getAttribute('d_table')->getFrontend()->getValue($_prods) != ''){
			$_prodstable[] = $_prods->getResource()->getAttribute('d_table')->getFrontend()->getValue($_prods);
		}
	}
	
	$options = Mage::getResourceModel('eav/entity_attribute_option_collection');
	$values  = $options->setAttributeFilter('d_cut')->setStoreFilter($storeId)->toOptionArray();
	$config    = Mage::getModel('eav/config');
	$attribute = $config->getAttribute(Mage_Catalog_Model_Product::ENTITY, 'd_cut');
	$values    = $attribute->setStoreId($storeId)->getSource()->getAllOptions();
	$_dcutarr = $_dcutValues = [];
	foreach($values as $key=>$val){
		if($val['label'] != ''){
			$_dcutarr[$val['label']] = $val['value'];
			$_dcutValues[] = $val['value'];
		}
	}
	$attribute = $config->getAttribute(Mage_Catalog_Model_Product::ENTITY, 'd_clarity');
	$values    = $attribute->setStoreId($storeId)->getSource()->getAllOptions();
	$_dclarr = $_dclValues = [];
	foreach($values as $key=>$val){
		if($val['label'] != '' && $val['label'] != 'I1' && $val['label'] != 'I2' && $val['label'] != 'I3'){
			$_dclarr[$val['label']] = $val['value'];
			$_dclValues[] = $val['value'];
		}
	}
	
	$attribute = $config->getAttribute(Mage_Catalog_Model_Product::ENTITY, 'd_polish');
	$values    = $attribute->setStoreId($storeId)->getSource()->getAllOptions();
	$_dpolish = $_dpolishValues =  [];
	foreach($values as $key=>$val){	
		if($val['label'] == 'GD' || $val['label'] == 'VG' || $val['label'] == 'EX'){
			$_dpolish[$val['label']] = $val['value'];
			$_dpolishValues[] = $val['value'];
		}
	}
	
	$attribute = $config->getAttribute(Mage_Catalog_Model_Product::ENTITY, 'd_fluorescence');
	$values    = $attribute->setStoreId($storeId)->getSource()->getAllOptions();
	$_dflu = $_dfluValues = [];
	foreach($values as $key=>$val){
		if($val['label'] != '' && $val['label'] != 'SLIGHT'){
			$_dflu[$val['label']] = $val['value'];
			$_dfluValues[] = $val['value'];
		}
	}
	
	$attribute = $config->getAttribute(Mage_Catalog_Model_Product::ENTITY, 'd_symmetry');
	$values    = $attribute->setStoreId($storeId)->getSource()->getAllOptions();
	$_dsym = $_dsymValues = [];
	foreach($values as $key=>$val){
		if($val['label'] == 'GD' || $val['label'] == 'VG' || $val['label'] == 'EX'){
			$_dsym[$val['label']] = $val['value'];
			$_dsymValues[] = $val['value'];
		}
	}
	
	
	
	
	
	
	$attribute = $config->getAttribute(Mage_Catalog_Model_Product::ENTITY, 'd_color');
	$values    = $attribute->setStoreId($storeId)->getSource()->getAllOptions();
	$_dclrarr = $_dclrValues = [];
	foreach($values as $key=>$val){
		if($val['label'] != ''){
			$_dclrarr[$val['label']] = $val['value'];
			$_dclrValues[] = $val['value'];
		}
	}
	
	$attribute = $config->getAttribute(Mage_Catalog_Model_Product::ENTITY, 'd_depth');
	$values    = $attribute->setStoreId($storeId)->getSource()->getAllOptions();
	$_ddepth = $_ddepthValues = [];
	foreach($values as $key=>$val){
		if($val['label'] != ''){
			$_ddepth[$val['label']] = $val['value'];
			$_ddepthValues[] = $val['value'];
		}
	}
	
	$attribute = $config->getAttribute(Mage_Catalog_Model_Product::ENTITY, 'd_table');
	$values    = $attribute->setStoreId($storeId)->getSource()->getAllOptions();
	$_dtbl = $_dtblValues = [];
	foreach($values as $key=>$val){
		if($val['label'] != ''){
			$_dtbl[$val['label']] = $val['value'];
			$_dtblValues[] = $val['value'];
		}
	}
	
		
	$products = Mage::getModel('catalog/category')->load(Mage::registry('current_category')->getId())
			   ->getProductCollection()
			   ->addStoreFilter(Mage::app()->getStore()->getId())
			   ->addAttributeToSelect('*')
			   ->addAttributeToFilter('status', 1)
			   ->addAttributeToSort('d_carat', 'ASC'); 
			   
			   
			   
	$pid = $products->getFirstItem()->getId();
	$plid = $products->getLastItem()->getId();



	$lCarat = Mage::getResourceModel('catalog/product')->getAttributeRawValue($pid, 'd_carat', $storeId);
	$hCarat = Mage::getResourceModel('catalog/product')->getAttributeRawValue($plid, 'd_carat', $storeId);
	
	sort($_prodscarats);
	$_prodscut = array_unique($_prodscut);
	sort($_prodscut);
	sort($_prodsdepth);
	sort($_prodstable);

	
	?>
    
    
    
    <div class="container">
      <div class="filters_div clearfix">
        <div class="block block-layered-nav">
          <div class="block-content">
            <div class="clearfix list_filters" id="narrow-by-list">
              <div class="filter_box">
                <div class="filter_title">Shape</div>
                <div class="filter_value">
                  <ol class="m-filter-item-list ">
                  <?PHP 
				  
				    $attribute = $config->getAttribute(Mage_Catalog_Model_Product::ENTITY, 'shape');
					$values    = $attribute->setStoreId($storeId)->getSource()->getAllOptions();
					$_dtbl = [];
					foreach($values as $key=>$val){
						if($val['label'] != ''){
							echo '
							<li class="shape_li_pull "> 
							<a href="#" class="btn-clr ajax-filter" data-filter="shape" data-value="'.$val['value'].'" title="'.(ucfirst($clr[$val['label']])).'" data-placement="bottom" data-toggle="tooltip"> <img width="auto" height="50" src="'.$this->getSkinUrl('packer/images/diamonds/'.$clr[($val['label'])].'.png').'" class="unchecked_img"></a></li>	
							';
						}
					}
				  ?>
                  </ol>
                </div>
              </div>
              
              <div class="filter_box">
                <div class="filter_title">Price</div>
                <div class="filter_value">
                  <ol class="m-filter-item-list ">
                    <?PHP 
					$minPrice=Mage::getSingleton('catalog/layer')->setCurrentCategory(Mage::registry('current_category'))
						->getProductCollection()->getMinPrice();
					$maxPrice=Mage::getSingleton('catalog/layer')->setCurrentCategory(Mage::registry('current_category'))
						->getProductCollection()->getMaxPrice();
	
				echo '
				<input class="dataurl" type="hidden" data-prefix="$"  value="" />
				<div class="range-inputs clearfix">
				<div class="range-input pull-left"><input type="text" class="form-control rangemin" value="$ '.$minPrice.'"/></div>
				<div class="range-input pull-right"><input type="text" class="form-control rangemax" value="$ '.$maxPrice.'"/></div>
				</div>
				<div class="rangeslider" data-filter="price" data-min-value="'.$minPrice.'" data-max-value="'.$maxPrice.'" data-min="'.$minPrice.'" data-max="'.$maxPrice.'"></div>';
					?>
                  </ol>
                </div>
              </div>
              
              
              <div class="filter_box">
                <div class="filter_title"> Carat 
                  <img class="info_title" src="<?PHP echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/base/default/packer/images/info.png"/>
                    <div class="popover fade bottom in mypop" style="position: fixed; top: 30px; left: -100px; width: 260px;">
                      <div class="arrow"></div>
                      <h3 class="pop-title">Carat (ct.)<a href="#" class="close_pop">x</a></h3>
                
                      <div class="popover-content text-center">
                      <p>
                      The international unit of weight, used for measuring diamonds and gemstones. 1 carat is equal to 200 milligrams, or 0.2 grams. 
                      </p>
                      
                      </div>
                    </div>
                </div>
                <div class="filter_value">
                  <ol class="m-filter-item-list ">
                    <?PHP
					$minPrice=$lCarat;
					$maxPrice=$hCarat;
					
	echo '
	<input class="dataurl" type="hidden" value="" />
	<div class="range-inputs clearfix">
	<div class="range-input pull-left"><input type="text" class="form-control rangemin" value="'.$minPrice.'"/></div>
	<div class="range-input pull-right"><input type="text" class="form-control rangemax" value="'.$maxPrice.'"/></div>
	</div>
	<div class="rangeslider" data-math="1000" data-filter="d_carat" data-min-value="'.$minPrice.'" data-max-value="'.$maxPrice.'" data-min="'.$minPrice.'" data-max="'.$maxPrice.'"></div>';
					
					
					?>
                  </ol>
                </div>
              </div>
              <div class="filter_box">
                <div class="filter_title"> Polish <img src="<?PHP echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/base/default/packer/images/info.png" class="info_title">
                  <div style="position: fixed; top: 30px; left: -100px; width: 260px;" class="popover fade bottom in mypop">
                    <div class="arrow"></div>
                    <h3 class="pop-title">Polish <a class="close_pop" href="#">x</a></h3>
                    <div class="popover-content text-center">
                      <p> The overall condition of a finished diamond's faceted surfaces, including how smoothly the facets have been polished, whether any marks are visible from the polishing wheel, and how defined the edges of each facet are. Polish marks are almost always invisible to the unaided eye, but good polish is essential for maximum light performance. </p>
                    </div>
                  </div>
                </div>
                <div class="filter_value">
                  <ol class="m-filter-item-list ">
                    <?PHP 
						
						$minPrice=0;
						$maxPrice=count($_dpolish);
						$tick_l = '';
						foreach($_dpolish as $pc=>$pcval){
							$tick_l .= '<span class="tick">'.(isset($lblVals[$pc]) ? $lblVals[$pc] : $pc).'</span>';
						}
						
						echo '
						<input class="dataurl" data-values=\''.(json_encode($_dpolishValues)).'\' type="hidden" value="" />
						<div class="ticker-inputs clearfix">
						'.$tick_l.'
						</div>
						<div  class="rangeslider" data-filter="d_polish" data-min-value="'.$minPrice.'" data-max-value="'.$maxPrice.'" data-min="'.$minPrice.'" data-max="'.$maxPrice.'" data-range="true"></div>
						';
					
					?>
                  </ol>
                </div>
              </div>
              <div class="filter_box">
                <div class="filter_title"> Symmetry <img src="<?PHP echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/base/default/packer/images/info.png" class="info_title">
                  <div style="position: fixed; top: 30px; left: -100px; width: 260px;" class="popover fade bottom in mypop">
                    <div class="arrow"></div>
                    <h3 class="pop-title">Symmetry <a class="close_pop" href="#">x</a></h3>
                    <div class="popover-content text-center">
                      <p>The precision and alignment of a diamond's facets and the resulting effects on its brilliance. 
                      <img src="<?PHP echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/base/default/packer/images/p_info/phab_item_symmetry.jpg" width="100%">
                      
                       </p>
                    </div>
                  </div></div>
                <div class="filter_value">
                  <ol class="m-filter-item-list ">
                    <?PHP
					$minPrice=0;
					$maxPrice=count($_dsym);
					$tick_l = '';
					foreach($_dsym as $pc=>$pcval){
						$tick_l .= '<span class="tick">'.(isset($lblVals[$pc]) ? $lblVals[$pc] : $pc).'</span>';
					}
					
					echo '
					<input class="dataurl" data-values=\''.(json_encode($_dsymValues)).'\' data-prefix="" data-split="d_carat=" type="hidden" value="" />
					<div class="ticker-inputs clearfix">
					'.$tick_l.'
					</div>
					<div class="rangeslider" data-filter="d_symmetry" data-min-value="'.$minPrice.'" data-max-value="'.$maxPrice.'" data-min="'.$minPrice.'" data-max="'.$maxPrice.'" data-range="true"></div>
					';	
					?>
                  </ol>
                </div>
              </div>
              <div class="filter_box">
                <div class="filter_title"> Fluorescence
                  <div class="filter-trigger-cont pull-right"><input type="checkbox" class="bSwitch triggerSwitch" data-size="mini"></div>
                    <img class="info_title" src="<?PHP echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/base/default/packer/images/info.png"/>
                    <div class="popover fade bottom in mypop" style="position: fixed; top: 30px; left: -100px; width: 260px;">
                      <div class="arrow"></div>
                      <h3 class="pop-title">Fluorescence <a href="#" class="close_pop">x</a></h3>
                
                      <div class="popover-content text-center">
                      <p>
                      A measure of the visible light some diamonds emit when exposed to ultraviolet (UV) rays. Diamonds with a strong or very strong fluorescence are a better value because the market prices them slightly lower. It is quite rare for fluorescence to have any visual impact on a diamond's appearance, and it does not compromise the gem's structural integrity in any way. 
                      </p>
                      
                      </div>
                    </div>
					
                </div>
                <div class="filter_value">
                  <ol class="m-filter-item-list  disable-range">
                    <?PHP
					$minPrice=0;
					$maxPrice=count($_dflu);
					$tick_l = '';
					foreach($_dflu as $pc=>$pcval){
						$tick_l .= '<span class="tick">'.(isset($lblVals[$pc]) ? $lblVals[$pc] : $pc).'</span>';
					}
					
					echo '
					<input class="dataurl" data-values=\''.(json_encode($_dfluValues)).'\' data-prefix="" data-split="d_carat=" type="hidden" value="" />
					<div class="ticker-inputs clearfix">
					'.$tick_l.'
					</div>
					<div class="rangeslider" data-disabled="true" data-filter="d_fluorescence" data-min-value="'.$minPrice.'" data-max-value="'.$maxPrice.'" data-min="'.$minPrice.'" data-max="'.$maxPrice.'" data-range="true"></div>
					';
					?>
                  </ol>
                </div>
              </div>
              <div class="filter_box">
                <div class="filter_title"> Cut 
                  <img class="info_title" src="<?PHP echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/base/default/packer/images/info.png"/>
                    <div class="popover fade bottom in mypop" style="position: fixed; width: 260px;">
                      <div class="arrow"></div>
                      <h3 class="pop-title">DIAMOND CUT <a href="#" class="close_pop">x</a></h3>
                
                      <div class="popover-content text-center">
                       <img class="cut_show_img" src="<?PHP echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/base/default/packer/images/cut/SIG_ID.png" />
                      
                      <div class="grey_box_con">
                      CHOOSE A CLARITY GRADE:
                      </div>
                      <div class="btn-grp-con">
                      <div class="mbtn mbtn-lg active" data-container=".cut_show_img" data-img="<?PHP echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/base/default/packer/images/cut/SIG_ID.png">
                      SIGNATURE IDEAL
                      </div>
                      <div class="mbtn mbtn-lg" data-container=".cut_show_img" data-img="<?PHP echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/base/default/packer/images/cut/EXCELLENT.png">
                      EXCELLENT
                      </div>
                      <div class="mbtn" data-container=".cut_show_img" data-img="<?PHP echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/base/default/packer/images/cut/VERY_GOOD.png">
                      VERY GOOD
                      </div>
                       <div class="mbtn" data-container=".cut_show_img" data-img="<?PHP echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/base/default/packer/images/cut/GOOD.png">
                      GOOD
                      </div>
                       <div class="mbtn" data-container=".cut_show_img" data-img="<?PHP echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/base/default/packer/images/cut/FAIR.png">
                      FAIR
                      </div>
                      </div>
                      
                      <p>
                      <b>Signature Ideal cut:</b> Top 1% of
diamond quality - with precise
proportions, polish and symmetry =
allowing the diamond to reflect even
more light than the standard Ideal cut.
                      </p>
                      
                      </div>
                    </div>
                </div>
                <div class="filter_value">
                  <ol class="m-filter-item-list ">
                    <?PHP
					$minPrice=0;
					$maxPrice=count($_dcutarr);
					$tick_l = '';
					foreach($_dcutarr as $pc=>$pcval){
						$tick_l .= '<span class="tick">'.(isset($lblVals[$pc]) ? $lblVals[$pc] : $pc).'</span>';
					}
					
					echo '
					<input class="dataurl" data-values=\''.(json_encode($_dcutValues)).'\' data-prefix="" data-split="d_carat=" type="hidden" value="" />
					<div class="ticker-inputs clearfix">
					'.$tick_l.'
					</div>
					<div class="rangeslider" data-filter="d_cut" data-min-value="'.$minPrice.'" data-max-value="'.$maxPrice.'" data-min="'.$minPrice.'" data-max="'.$maxPrice.'" data-range="true"></div>
					';
					?>
                  </ol>
                </div>
              </div>
              <div class="filter_box">
                <div class="filter_title"> color
                <img class="info_title" src="<?PHP echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/base/default/packer/images/info.png"/>
                    <div class="popover fade bottom in mypop" style="position: fixed; top: 30px; left: -100px; width: 260px;">
                      <div class="arrow"></div>
                      <h3 class="pop-title">DIAMOND COLOUR <a href="#" class="close_pop">x</a></h3>
                
                      <div class="popover-content text-center">
                       <img class="color_show_img" src="<?PHP echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/base/default/packer/images/color/color_df.png" />
                      
                      <div class="grey_box_con">
                      CHOOSE A COLOUR GRADE:
                      </div>
                      <div class="btn-grp-con">
                      <div class="mbtn mbtn-lg active" data-container=".color_show_img" data-img="<?PHP echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/base/default/packer/images/color/color_df.png">
                      D-F
                      </div>
                      <div class="mbtn mbtn-lg" data-container=".color_show_img" data-img="<?PHP echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/base/default/packer/images/color/color_gi.png">
                     	G-I
                      </div>
                      <div class="mbtn" data-container=".color_show_img" data-img="<?PHP echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/base/default/packer/images/color/color_jk.png">
                      J-K
                      </div>
                      
                      </div>
                      
                      <p>
                      Highest,  absolutely colourless grade,appreciated best set in platinum orwhite gold. Exceptionally rare.
                      </p>
                      
                      </div>
                    </div>
                </div>
                <div class="filter_value">
                  <ol class="m-filter-item-list ">
                 	<?PHP
					$minPrice=0;
					$maxPrice=count($_dclrarr);
					$tick_l = '';
					foreach($_dclrarr as $pc=>$pcval){
						$tick_l .= '<span class="tick">'.(isset($lblVals[$pc]) ? $lblVals[$pc] : $pc).'</span>';
					}
					
					echo '
					<input class="dataurl" data-values=\''.(json_encode($_dclrValues)).'\' data-prefix="" data-suffix="" data-split="d_carat=" type="hidden" value="" />
					<div class="ticker-inputs clearfix">
					'.$tick_l.'
					</div>
					<div class="rangeslider" data-filter="d_color" data-min-value="'.$minPrice.'" data-max-value="'.$maxPrice.'" data-min="'.$minPrice.'" data-max="'.$maxPrice.'" data-range="true"></div>
					';
					?>
                  </ol>
                </div>
              </div>
              <div class="filter_box">
                <div class="filter_title"> Clarity 
                 <img class="info_title" src="<?PHP echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/base/default/packer/images/info.png"/>
                    <div class="popover fade bottom in mypop" style="position: fixed; top: 30px; left: -100px; width: 260px;">
                      <div class="arrow"></div>
                      <h3 class="pop-title">DIAMOND CLARITY <a href="#" class="close_pop">x</a></h3>
                
                      <div class="popover-content text-center">
                       <img class="clr_show_img" src="<?PHP echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/base/default/packer/images/clarity/cl_vfl-tl.png" />
                      
                      <div class="grey_box_con">
                      CHOOSE A CLARITY GRADE:
                      </div>
                      <div class="btn-grp-con">
                      <div class="mbtn mbtn-lg active" data-container=".clr_show_img" data-img="<?PHP echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/base/default/packer/images/clarity/cl_vfl-tl.png">
                      FL-IF
                      </div>
                      <div class="mbtn mbtn-lg" data-container=".clr_show_img" data-img="<?PHP echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/base/default/packer/images/clarity/cl_vvs1-vvs2.png">
                      VVS1-VVS2
                      </div>
                      <div class="mbtn" data-container=".clr_show_img" data-img="<?PHP echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/base/default/packer/images/clarity/cl_vs1-vs2.png">
                     VS1-VS2	
                      </div>
                       <div class="mbtn" data-container=".clr_show_img" data-img="<?PHP echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/base/default/packer/images/clarity/cl_si1-si2.png">
                      SI1-SI2
                      </div>
                       
                      </div>
                      
                      <p>
                      <b>FLAWLESS</b>: NO INTERNAL OR EXTERNAL
CHARACTERISTICS. INTERNALLY FLAWLESS:
MAY HAVE EXTERNAL BLEMISHES ONLY. BOTH
EXTREMELY RARE.
                      </p>
                      
                      </div>
                    </div>
                </div>
                <div class="filter_value">
                  <ol class="m-filter-item-list ">
                    <?PHP
						$minPrice=0;
						$maxPrice=count($_dclarr);
						$tick_l = '';
						foreach($_dclarr as $pc=>$pcval){
							$tick_l .= '<span class="tick">'.(isset($lblVals[$pc]) ? $lblVals[$pc] : $pc).'</span>';
						}
						
						echo '
						<input class="dataurl" data-values=\''.(json_encode($_dclValues)).'\' data-prefix="" data-split="d_carat=" type="hidden" value="" />
						<div class="ticker-inputs clearfix">
						'.$tick_l.'
						</div>
						<div class="rangeslider" data-filter="d_clarity" data-min-value="'.$minPrice.'" data-max-value="'.$maxPrice.'" data-min="'.$minPrice.'" data-max="'.$maxPrice.'" data-range="true"></div>
						';
					?>
                  </ol>
                </div>
              </div>
              
              
              <div class="filter_box">
                <div class="filter_title"> Depth
                  <div class="filter-trigger-cont pull-right"><input type="checkbox" class="bSwitch triggerSwitch" data-size="mini"></div>
                    <img class="info_title" src="<?PHP echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/base/default/packer/images/info.png"/>
                    <div class="popover fade bottom in mypop" style="position: fixed; top: 30px; left: -100px; width: 260px;">
                      <div class="arrow"></div>
                      <h3 class="pop-title">Depth percentage <a href="#" class="close_pop">x</a></h3>
                
                      <div class="popover-content text-center">
                      <p>
                      The height of a diamond, measured from the culet to the table, divided by its average girdle diameter. One of the basic proportions that contributes to a diamond's appearance, brilliance and fire. 
                      </p>
                      
                      </div>
                    </div>
                </div>
                <div class="filter_value">
                  <ol class="m-filter-item-list  disable-range">
                   	<?PHP
					$minPrice=$_prodsdepth[0];
					$maxPrice=$_prodsdepth[count($_prodsdepth)-1];
					$tick_l = '';
					foreach($_ddepth as $pc=>$pcval){
						$tick_l .= '<span class="tick">'.$pc.'</span>';
					}
					
					echo '
					<input class="dataurl" data-values=\''.(json_encode($_ddepthValues)).'\' data-prefix="" data-suffix="%" data-split="d_carat=" type="hidden" value="" />
					<div class="range-inputs clearfix">
					<div class="range-input pull-left"><input type="text" class="form-control rangemin" value="'.$minPrice.'%"/></div>
					<div class="range-input pull-right"><input type="text" class="form-control rangemax" value="'.$maxPrice.'%"/></div>
					</div>
					<div class="rangeslider" data-disabled="true" data-filter="d_depth" data-min-value="'.$minPrice.'" data-max-value="'.$maxPrice.'" data-min="'.$minPrice.'" data-max="'.$maxPrice.'" data-range="true"></div>
					';
					?> 
                  </ol>
                </div>
              </div>
              <div class="filter_box">
                <div class="filter_title"> Table
                  <div class="filter-trigger-cont pull-right"><input type="checkbox" class="bSwitch triggerSwitch" data-size="mini"></div>
                    <img class="info_title" src="<?PHP echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/base/default/packer/images/info.png"/>
                    <div class="popover fade bottom in mypop" style="position: fixed; top: 30px; left: -100px; width: 260px;">
                      <div class="arrow"></div>
                      <h3 class="pop-title">Table percentage <a href="#" class="close_pop">x</a></h3>
                
                      <div class="popover-content text-center">
                      <p>
                      The width of the diamond's table expressed as a percentage of its average diameter. A component of the overall cut grade, this measurement is critical to a diamond's light performance. 
                      </p>
                      
                      </div>
                    </div>
                </div>
                <div class="filter_value">
                  <ol class="m-filter-item-list  disable-range">
                   <?PHP
				   $minPrice=$_prodstable[0];
					$maxPrice=$_prodstable[count($_prodstable)-1];
					$tick_l = '';
					foreach($_dtbl as $pc=>$pcval){
						$tick_l .= '<span class="tick">'.(isset($lblVals[$pc]) ? $lblVals[$pc] : $pc).'</span>';
					}
					
					echo '
					<input class="dataurl" data-values=\''.(json_encode($_dtblValues)).'\' data-prefix="" data-suffix="%" data-split="d_carat=" type="hidden" value="" />
					<div class="range-inputs clearfix">
					<div class="range-input pull-left"><input type="text" class="form-control rangemin" value="'.$minPrice.'%"/></div>
					<div class="range-input pull-right"><input type="text" class="form-control rangemax" value="'.$maxPrice.'%"/></div>
					</div>
					<div class="rangeslider" data-disabled="true" data-filter="d_table" data-min-value="'.$minPrice.'" data-max-value="'.$maxPrice.'" data-min="'.$minPrice.'" data-max="'.$maxPrice.'" data-range="true"></div>
					';
				   ?>
                   </ol>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="clearfix"> <a class="btn-no-border pull-left" href="#"><img src="<?PHP echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/base/default/packer/images/reset-icon-60.png" /> RESET FILTERS</a> <a class="btn-border-grey pull-right filter_slider" data-position="1" href="#"><!--<i class="fa fa-long-arrow-left"></i> BASIC FILTERS--> 
          ADVANCE FILTERS <i class="fa fa-long-arrow-right"></i> </a> </div>
      </div>
      <div class="filter_trigger_div text-center"> <a class="filter_trigger" href="#">View Filters <i class="fa fa-long-arrow-down"></i></a> </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
	$clr = array();
	$clr['AS'] = 'asscher';
	$clr['CU'] = 'cushion';
	$clr['EC'] = 'emerald';
	$clr['HS'] = 'heart';
	$clr['MQ'] = 'marquise';
	$clr['OV'] = 'oval';
	$clr['PR'] = 'pear';
	$clr['PS'] = 'princess';
	$clr['RA'] = 'radiant';
	$clr['RD'] = 'round';
?>
      <?php if(!$_productCollection->count()): ?>
      <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
      <?php else: ?>
      <div class="category-products">
        <div class="clearfix pv30 mystylefont row">
          <div class="col-md-6"> <a class="fcdark compareItems" href="javascript:void(0);">Compare your Diamonds <span class="cmp_count">(0)</span> <i class="fa fa-long-arrow-right pl30"></i></a> <a href="javascript:void(0);" class="fcdark backTosearch mystylefont"> <i class="fa fa-long-arrow-left pr30"></i> Back to Search</a> </div>
          <div class="col-md-6 text-right"> <span class="total_results"><?PHP echo $_productCollection->getSize(); ?></span> results found </div>
        </div>
        <div class="cat-results">
          <div class="items-table-container">
          <div class="loader-opacity-div"><img src="<?PHP echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/base/default/packer/images/loader.gif" /></div>
          
            <div class="item-list-all">
            <div class="fixed-table-header">
            <div class="cell-compare">Compare</div>
            <div class="cell-shape">Shape</div>
            <div class="cell-carat">Carat</div>
            <div class="cell-color">Color</div>
            <div class="cell-clarity">Clarity</div>
            <div class="cell-cut">Cut</div>
            <div class="cell-polish">Polish</div>
            <div class="cell-symm">SYMMETRY</div>
            <div class="cell-price">Price</div>
            </div>
            <div class="item-list-table">
              <table class="table-hover text-center table-bordered my-custom-list-table" width="100%">
                <tbody>
                  <?php $_iterator = 0; $_even = 0; ?>
                  <?php foreach ($_productCollection as $_product):
				  
				  $dclarity = $_product->getAttributeText('d_clarity');
				  $dcut = $_product->getAttributeText('d_cut');
				  $dpolish = $_product->getAttributeText('d_polish');
				  $dsym = $_product->getAttributeText('d_symmetry');
				  
				   ?>
                  <tr data-id="<?PHP echo $_product->getId(); ?>" class="item_ajax_get_details" <?PHP echo ($_even % 2 == 0 ? 'class="grey-bg"' : '') ?>>
                    <td class="cell-compare"><input class="compare_item" type="checkbox" name="chk[]" value="" /></td>
                    <?php /* echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(30); */ ?>
                    <td class="cell-shape text-center list-img-label text-uppercase"><img src="<?PHP echo $this->getSkinUrl('packer/images/diamonds/'.$clr[$_product->getAttributeText('shape')].'.png'); ?>" width="auto" height="20" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /> <?PHP echo $clr[$_product->getAttributeText('shape')]; ?></td>
                    <td class="cell-carat"><?PHP echo round($_product->getResource()->getAttribute('d_carat')->getFrontend()->getValue($_product),2); ?></td>
                    <td class="cell-color"><?PHP echo $_product->getAttributeText('d_color'); ?></td>
                    <td class="cell-clarity"><?PHP echo (isset($lblVals[$dclarity]) ? $lblVals[$dclarity] : $dclarity); ?></td>
                    <td class="cell-cut"><?PHP echo (isset($lblVals[$dcut]) ? $lblVals[$dcut] : $dcut); ?></td>
                    <td class="cell-polish"><?PHP echo (isset($lblVals[$dpolish]) ? $lblVals[$dpolish] : $dpolish); ?></td>
                    <td class="cell-symm"><?PHP echo (isset($lblVals[$dsym]) ? $lblVals[$dsym] : $dsym); ?></td> 
                    <td class="cell-price">SGD $<?PHP echo sprintf('%0.2f', $_product->getPrice()); ?> <i class="fa fa-arrow-right pl30"></i></td>
                  </tr>
                  <?php $_even++; endforeach; ?>
                </tbody>
              </table>
            </div>
            </div>
            <div class="item-compare-list">
              <div class="loader-opacity-div"><img src="<?PHP echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/base/default/packer/images/loader.gif" /></div>
              <div class="mystylefont"> Compare your diamonds <span class="cmp_count">(0)</span> </div>
              <table id="compareTable" class="table-hover text-center table-bordered my-custom-list-table" width="100%">
                <thead>
                  <tr>
                    <th class="text-center">Remove</th>
                    <th class="text-center">Shape</th>
                    <th class="text-center">Carat</th>
                    <th class="text-center">Cut</th>
                    <th class="text-center">Color</th>
                    <th class="text-center">Clarity</th>
                    <th class="text-center">Price</th>
                  </tr>
                </thead>
                <tbody>
                </tbody>
              </table>
            </div>
          </div>
          <div class="item-info-block">
            <div class="loader-opacity-div"><img src="<?PHP echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/base/default/packer/images/loader.gif" /></div>
            <div class="item-info-ajax-container"> </div>
          </div>
        </div>
      </div>
      <?php endif; ?>
    </div>
  </div>
</div>
<script>
     var BASE_URL='<?php echo Mage::getBaseUrl();?>';
	 var categoryId = <?PHP echo Mage::registry('current_category')->getId(); ?>
</script>