<?php
$selectedJewellerygiftMaincat = Mage::getSingleton('core/session')->getJewellerygiftMaincat();
$selectedJewellerygiftStyle = Mage::getSingleton('core/session')->getJewellerygiftStyle();

if ($_GET['maincat'] != '') {
    $maincat = $_GET['maincat'];
} else {
    $maincat = $selectedJewellerygiftMaincat;
}

if ($_GET['style'] != '') {
    $style = strtolower($_GET['style']);
} else {
    $style = $selectedJewellerygiftStyle;
}


$dataJewellSettingValues = array();
$dataJewellSettingEngravableValues = array();
$setengravable='0';

$dataJewellSettingValues = array(27 => 'Necklaces', 106 => 'Rings', 28 => 'Earrings', 29 => 'Bracelets');
switch ($maincat) {
    case 'necklace':
        $category = Mage::getModel('catalog/category')->load(27);
        $subcategories = $category->getChildrenCategories();
        if (count($subcategories) > 0) {
            foreach ($subcategories as $subcategory) {
                if ($style == strtolower(str_replace(" ", "-", $subcategory->getName()))) {
                    $maincat_id = $subcategory->getId();
                    $maincat_name = strtolower(str_replace(" ", "-", $subcategory->getName()));
                    switch ($style) {
						case 'diamond':

							$searchfor = 'pendant_types';
							break;
						case 'pearl':
							$dataJewellSettingValues = array(140 => 'Water', 139 => 'Akoya', 138 => 'Tahitian', 144 => 'South Sea Pearl');
							$searchfor = 'pearl_types';
							break;
						case 'engravable':
							$mainengravable='27';
							$setengravable='1';
							$dataJewellSettingEngravableValues = array(27 => array('Pendants','necklace/engravable','jewellery-necklaces.php?maincat=necklace&style=engravable'), 29 => array('Bracelets','bracelet/engravable','jewellery-bracelets.php?maincat=bracelet&style=engravable'), 84 => array('Gifts','gift/engravable','jewellery-gifts.php?maincat=gift&style=engravable'));
							break;	
                    }
                }

                $dataSettingValue['necklace'][$subcategory->getId()] = $subcategory->getName();
            }
        }
        break;
    case 'earrings':
        $category = Mage::getModel('catalog/category')->load(28);
        $subcategories = $category->getChildrenCategories();
        if (count($subcategories) > 0) {
            foreach ($subcategories as $subcategory) {
                if ($style == strtolower(str_replace(" ", "-", $subcategory->getName()))) {
                    $maincat_id = $subcategory->getId();
                    $maincat_name = strtolower(str_replace(" ", "-", $subcategory->getName()));
                    switch ($style) {
                        case 'diamond':
                            //$dataJewellSettingValues = array(137 => 'Stud');
							//$dataJewellSettingValues = array(135 => 'Fancy', 137 => 'Stud');
							$dataJewellSettingValues = array(135 => 'Fancy', 136 => 'Hoops', 137 => 'Stud', 145 => 'Others');
                            $searchfor = 'earrings_types';
                            break;
                        case 'pearl':
                            $dataJewellSettingValues = array(140 => 'Water', 139 => 'Akoya', 138 => 'Tahitian', 144 => 'South Sea Pearl');
                            $searchfor = 'pearl_types';
                            break;
                    }
                }

                $dataSettingValue['earrings'][$subcategory->getId()] = $subcategory->getName();
            }
        }
        break;
    case 'bracelet':
        $category = Mage::getModel('catalog/category')->load(29);
        $subcategories = $category->getChildrenCategories();
        if (count($subcategories) > 0) {
            foreach ($subcategories as $subcategory) {
                if ($style == strtolower(str_replace(" ", "-", $subcategory->getName()))) {
                    $maincat_id = $subcategory->getId();
                    $maincat_name = strtolower(str_replace(" ", "-", $subcategory->getName()));
                    switch ($style) {
                        case 'diamond':
                            //$dataJewellSettingValues = array(137 => 'Stud');
							//$dataJewellSettingValues = array(135 => 'Fancy', 137 => 'Stud');
							//$dataJewellSettingValues = array(135 => 'Fancy', 136 => 'Hoops', 137 => 'Stud', 145 => 'Others');
							$dataJewellSettingValues = array(141 => 'Bangle', 142 => 'Tennis', 143 => 'Others');
                            $searchfor = 'bracelet_types';
                            break;
                        case 'pearl':
                            $dataJewellSettingValues = array(140 => 'Water', 139 => 'Akoya', 138 => 'Tahitian', 144 => 'South Sea Pearl');
                            $searchfor = 'pearl_types';
                            break;
						case 'engravable':
						    $mainengravable='29';
							$setengravable='1';
                            $dataJewellSettingEngravableValues = array(27 => array('Pendants','necklace/engravable','jewellery-necklaces.php?maincat=necklace&style=engravable'), 29 => array('Bracelets','bracelet/engravable','jewellery-bracelets.php?maincat=bracelet&style=engravable'), 84 => array('Gifts','gift/engravable','jewellery-gifts.php?maincat=gift&style=engravable'));
                            break;	
                    }
                }

                $dataSettingValue['bracelet'][$subcategory->getId()] = $subcategory->getName();
            }
        }
        break;
	case 'gift':
        $category = Mage::getModel('catalog/category')->load(84);
        $subcategories = $category->getChildrenCategories();
		
        if (count($subcategories) > 0) {
            foreach ($subcategories as $subcategory) {
			
                if ($style == strtolower(str_replace(" ", "-", $subcategory->getName()))) {
                    $maincat_id = $subcategory->getId();
                    $maincat_name = strtolower(str_replace(" ", "-", $subcategory->getName()));
                    switch ($style) {
                        case 'diamond':
							$dataJewellSettingValues = array(135 => 'Fancy', 136 => 'Hoops', 137 => 'Stud', 145 => 'Others');
                            $searchfor = 'earrings_types';
                            break;
                        case 'engravable':
						    $mainengravable='84';
							$setengravable='1';
                            $dataJewellSettingEngravableValues = array(27 => array('Pendants','necklace/engravable','jewellery-necklaces.php?maincat=necklace&style=engravable'), 29 => array('Bracelets','bracelet/engravable','jewellery-bracelets.php?maincat=bracelet&style=engravable'), 84 => array('Gifts','gift/engravable','jewellery-gifts.php?maincat=gift&style=engravable'));
                            break;
                    }
                }

                $dataSettingValue['earrings'][$subcategory->getId()] = $subcategory->getName();
            }
        }
        break;	
	case 'jewellery-rings':
        $category = Mage::getModel('catalog/category')->load(106);
        $subcategories = $category->getChildrenCategories();
        if (count($subcategories) > 0) {
            foreach ($subcategories as $subcategory) {
                if ($style == strtolower(str_replace(" ", "-", $subcategory->getName()))) {
                    $maincat_id = $subcategory->getId();
                    $maincat_name = strtolower(str_replace(" ", "-", $subcategory->getName()));
			switch ($style) {
				case 'gemstone':
				$dataJewellSettingValues = array(149 => 'Emerald', 150 => 'Morganite', 151 => 'Ruby', 152 => 'Shapphire', 153 => 'Tanzanite', 154 => 'Others');
				$searchfor = 'ring_gamestone';
				break;
			}
                }

                $dataSettingValue['bracelet'][$subcategory->getId()] = $subcategory->getName();
            }
        }
        break;
}

if ($maincat_id == '') {
    Mage::app()->getFrontController()->getResponse()->setRedirect(Mage::getBaseUrl())->sendResponse();
    exit;
}

$dataSettingValues = $dataSettingValue;

$attributeStyleArys = array('White Gold', 'Yellow Gold', 'Rose Gold');
$attributeMetalArys = array('14k', '18k', 'Platinum');

//Load product model collecttion filtered by attribute set id Mage::getModel('catalog/category')->load(3)
if (isset($_GET['order'])) {
    $orderby = $_GET['order'];
} else {
    $orderby = 'name';
}
//echo $maincat_id;

		
$products = Mage::getModel('catalog/product')
    ->getCollection()
    ->joinField('category_id', 'catalog/category_product', 'category_id', 'product_id = entity_id', null, 'left')
    ->addAttributeToSelect('*')
	->setPageSize(12)
	->addAttributeToFilter('status', 1)
    ->addAttributeToFilter('category_id', array(
        array('finset' => '27'),
        array('finset' => '28'),
		array('finset' => '29'),
		array('finset' => '106')
		)
    )
    ->addAttributeToSort($orderby, 'asc');
	
			
$collection = Mage::getModel('catalog/product')
    ->getCollection()
    ->joinField('category_id', 'catalog/category_product', 'category_id', 'product_id = entity_id', null, 'left')
    ->addAttributeToSelect('*')
	->addAttributeToFilter('status', 1)
    ->addAttributeToFilter('category_id', array(
        array('finset' => '27'),
        array('finset' => '28'),
		array('finset' => '29'),
		array('finset' => '106')
		)
    )
    ->addAttributeToSort($orderby, 'asc');

$products->addAttributeToFilter('metals', array(
        array('finset' => '126'),
        array('finset' => '127'),
		array('finset' => '128')
		));
$collection->addAttributeToFilter('metals', array(
        array('finset' => '126'),
        array('finset' => '127'),
		array('finset' => '128')
		));

$products->addAttributeToFilter('color_metals', array(
        array('finset' => '146'),
        array('finset' => '147'),
		array('finset' => '148')
		));
$collection->addAttributeToFilter('color_metals', array(
        array('finset' => '146'),
        array('finset' => '147'),
		array('finset' => '148')
		));		
		
				
if (Mage::app()->getStore()->getDefaultCurrencyCode() != Mage::app()->getStore()->getCurrentCurrencyCode()) {
	$allowedCurrencies = Mage::getModel('directory/currency')->getConfigAllowCurrencies();
	$currentRate = Mage::getModel('directory/currency')->getCurrencyRates(Mage::app()->getStore()->getCurrentCurrencyCode(), array_values($allowedCurrencies));

	$luxuryprice = round(Mage::helper('directory')->currencyConvert(10000 - 2, 'USD', 'SGD'));
	$under150price = round(Mage::helper('directory')->currencyConvert(150 - 2, 'USD', 'SGD'));
} else {
	$luxuryprice = '10000';
	$under150price = '150';
}
			
	if($style=='luxury')
	{
	$products->addAttributeToFilter('price', array('gt' => $luxuryprice));
	$collection->addAttributeToFilter('price', array('gt' => $luxuryprice));
	}
	if($style=='gift-under-$150')
	{
	$products->addAttributeToFilter('price', array('lt' => $under150price));
	$collection->addAttributeToFilter('price', array('lt' => $under150price));
	}
$allowedProducts = array();

$total_pages = $products->getLastPageNumber();

/*echo $products->count();
echo"<br>";
echo $collection->count();*/
foreach ($products as $product) {
    if ($selectedDiamondType) {
        array_push($allowedProducts, $product);
    } else {
        array_push($allowedProducts, $product);
    }
}

// Getting product max and min prices
$all_prices = array();

foreach ($collection as $p) {
    array_push($all_prices, $p->getPrice());
}

$min_price = min($all_prices);
$max_price = max($all_prices);

$_currentCurrencyCode = Mage::app()->getStore()->getCurrentCurrencyCode();
if ($_currentCurrencyCode == 'USD') {
    $min_price = Mage::helper('directory')->currencyConvert($min_price, 'SGD', 'USD');
    $max_price = Mage::helper('directory')->currencyConvert($max_price, 'SGD', 'USD');
}

//$min_price--;
$min_price = '0';
$max_price++;

echo $this->getCurrentDirection();
$_category = Mage::getModel('catalog/category')->load($maincat_id);
$_imgHtml = '';
//echo  $products->getSelect();
?>
<script type="text/javascript">
    window.ringFilterUrl = '<?php echo Mage::getBaseUrl(); ?>diamonds/ajax/filterjewellerygiftring';
    window.ringTotalPages = '<?php echo $collection->count(); ?>';</script>
<style>
    .nav-1 .color-menu-thumb {
        max-height: 39px  !important;
        max-width: 35px  !important;
        margin-top: 0;
    }
    .filters-step-colours .filter li a.checked::after {
        background: #b0cde9 none repeat scroll 0 0;
        border-radius: 5px;
        color: #fff !important;
        content: " ";
        display: block;
        height: 29px;
        left: 20px;
        margin-top: 3px;
        position: absolute;
        top: 1px;
        width: 65%;
        z-index: -1;
    }
    .small-configurable > li {
        float: left;     
		text-align: center;  
    }
    .subspan {
        float: left;
        margin-top: -5px;
        position: relative;
        width: 100%;
		font-size: 11px;
        z-index: 999;
    }
    .sidebar-thumb-style {
        max-width: 40px;
        vertical-align: middle;
    }
    
        .category-products .products-grid .itemwedding .product-content {
            padding: 10px 0 !important;
        }
       
    .filters-step-2 .style li a.checked::after {
        background-image: radial-gradient(circle closest-side, #b0cde9, rgba(0, 0, 0, 0));
        content: " ";
        display: block;
        height: 33px;
        left: 29px;
        position: absolute;
        top: 1px;
        width: 33px;
        z-index: -1;
    }

</style>



<div class="main-wrapper">
    <div class="container">
        <div class="main">
            <div class="row show-grid">
                <div class="col-lg-12">
                    <div class="site-preface"></div>
                </div>
            </div>
            <div class="row show-grid">
                <div class="col-lg-12"></div>
            </div>
            <div class="row show-grid">
                <div class="col-lg-3 sidebar">
                    <div class="col-left">
                        <!-- Category Navigation BOF -->
                        <div class="block block-nav filters-step-2">
                            <div class="block-title"> <strong><span>Categories</span></strong> </div>
                            <div class="block-content">
                                <ul class="nav-accordion nav-categories" id="categories_nav" style="">
                                    <?php 
									if(!empty($dataJewellSettingValues))
									{
									?>
									<li class="level0 nav-1 level-top first parent"> <a class="level-top" href="javascript:;"><span>PRODUCT TYPE</span></a>
                                        <ul class="level0 no-bullets filter style" id="styles_up"  data-filter="style" style="display: block;">

                                            <?php
                                            $i = 0;
                                            foreach ($dataJewellSettingValues as $key => $value) {
                                                ?>
                                                <li class="level1 item nav-1-1 <?php echo ($i == 0) ? 'first' : ''; ?>"> <a id="style_list_<?php echo $key; ?>" class="checked" data-value='<?php echo str_replace(" ", "-", $value); ?>' href="javascript:;"> <span><?php echo $value; ?></span></a> </li>
                                                <?php
                                                $i++;
                                            }
                                            ?>
                                        </ul>
                                    </li>
									<?php
									}
																		
									if(!empty($dataJewellSettingEngravableValues))
									{
									?>
									<li class="level0 nav-1 level-top first parent"> <a class="level-top" href="javascript:;"><span>PRODUCTS</span></a>
                                        <ul class="level0 no-bullets engravable" id="styles_up"  style="display: block;">

                                            <?php
                                            $i = 0;
                                            foreach ($dataJewellSettingEngravableValues as $key => $value) {
                                              $csschecked="";
											  if($mainengravable==$key)
											  {
											  $csschecked='checked';
											  }
											  //print_r($value);
                                                ?>
                                                <li class="level1 item nav-1-1 <?php echo ($i == 0) ? 'first' : ''; ?>">
												 <a class="go-to-step-one-jewellery-gifts <?php echo $csschecked ?>" jewellerygifts="<?php echo $value[1] ?>" href="<?php echo Mage::getBaseUrl().$value[2]; ?>">
                                        <span><?php echo $value[0] ?></span>
                                            </a>
												 </li>
                                                <?php
                                                $i++;
                                            }
                                            ?>
                                        </ul>
                                    </li>
									<?php
									}
									?>
                                    <li class="level0 nav-1 level-top parent filters-step-colours"> <a class="level-top" href="javascript:;"><span>COLOURS</span></a>
                                        <ul class="level0 no-bullets filter colours" id="colours_list" data-filter="colours" style="display:<?php echo $selectedDiamondType == '' ? 'block' : 'none'; ?>">
                                            <?php
                                            foreach ($attributeStyleArys as $key => $value) {
                                                ?>
                                                <li class="level1 item nav-1-1 <?php if ($key == 0) { ?> first <?php } ?>"> 
                                                    <a  id="colours_list_<?php echo $key; ?>" class="checked" href="javascript:;"  data-value='<?php echo strtolower(str_replace(" ", "-", $value)); ?>' >
                                                        <img class="menu-thumb-small color-menu-thumb" src="<?php echo Mage::getBaseUrl(); ?>media/catalog/category/<?php echo strtolower(str_replace(" ", "-", $value)); ?>.png" alt=""> 
                                                        <span><?php echo ucwords($value); ?></span>
                                                    </a> 
                                                </li>
                                                <?php
                                            }
                                            ?>
                                        </ul>
                                    </li>
                                    <li class="level0 nav-1 level-top parent filters-step-metals"> <a class="level-top" href="javascript:;"><span>METALS</span></a>
                                        <ul class="level0 no-bullets filter metals" id="metals_list" data-filter="metals" style="display:<?php echo $selectedDiamondType == '' ? 'block' : 'none'; ?>">
                                            <?php
                                            foreach ($attributeMetalArys as $key => $value) {
                                                ?>
                                                <li class="level1 item nav-1-1 <?php if ($key == 0) { ?> first <?php } ?>"> 
                                                    <a  id="metals_list_<?php echo $key; ?>" class="checked" href="javascript:;"  data-value='<?php echo strtolower(str_replace(" ", "-", $value)); ?>' >
                                                        <span><?php echo ucwords($value); ?></span>
                                                    </a> 
                                                </li>
                                                <?php
                                            }
                                            ?>
                                        </ul>
                                    </li>
                                    <li class="level0 nav-1 level-top parent last"> <a class="level-top" href="javascript:;"><span>PRICES</span></a>
                                        <table class="prices-data" width="100%" style="margin-bottom: 17px;">
                                            <tr>
                                                <?php $currSymbol = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol(); ?>
                                                <td style="padding-left: 18px;"><span class="value-from"><?php echo $currSymbol . number_format($min_price); ?></span></td>
                                                <td align="right"><span class="value-to"><?php echo $currSymbol . number_format($max_price); ?></span></td>
                                            </tr>
                                        </table>
                                        <div class="rangeslider-s2 sidebar-price-slider" data-filter="price" data-min-value="" data-max-value="" data-min="" data-max=""></div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <!-- Category Navigation EOF -->
                        <div class="block block-list block-compare">
                            <div class="block-title"> <strong><span>Compare</span></strong> </div>
                            <div class="block-content">
                                <p class="empty">You have no items to compare.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="col-main category-products">

                        <?php
                        if ($_imgUrl = $_category->getImageUrl()) {
                            $_imgHtml = '<p class="category-image"><img class="img-responsive" src="' . $_imgUrl . '" alt="' . $this->escapeHtml($_category->getName()) . '" title="' . $this->escapeHtml($_category->getName()) . '" /></p>';
                        }
                        ?>
                        <?php if ($_imgUrl): ?>
                            <?php echo $_imgHtml ?>
                            <?php
                        endif;
                        if ($style != 'classic') {
                            ?>  
                            <div class="toolbar">
                                <div class="row">
                                    <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
                                        <div class="row">
                                            <div class="col-lg-9">
                                                <div class="sorter_wrap">
                                                    <div class="sort-by">
                                                        <div class="select-new">
                                                            <div class="select-inner"> <span>Sort by: </span>
                                                                <div aria-expanded="false" href="#sort_by" data-toggle="collapse" id="sort_by_main" role="button" class="overwrite-sortby">Name</div>
                                                                <ul class="sort_by in" id="sort_by" style="height: auto;">
                                                                    <li> <a href="&order=name" data-value="Name">Name</a> </li>
                                                                    <li> <a href="&order=style" data-value="Style">Style</a> </li>
                                                                    <li> <a href="&order=price" data-value="Price">Price</a> </li>
                                                                </ul>
                                                            </div>
                                                        </div>
                                                        <div class="direction-list"> 
                                                            <a title="Set Descending Direction" id="desc_by_dir" style="display: block;" data-dire="desc" href="&dir=desc" class="direction direction-up" style="line-height:1.8;">
                                                                <i class="fa fa-arrow-up"></i>
                                                            </a> 
                                                            <a title="Set Ascending Direction" id="asc_by_dir" style="display: none;"  data-dire="asc" href="&dir=asc" class="direction direction-down" style="line-height:1.8;">
                                                                <i class="fa fa-arrow-down"></i>
                                                            </a> 
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="limiter_wrap">
                                                    <div class="limiter">
                                                        <div class="select-new">
                                                            <div class="select-inner">
                                                                <div aria-expanded="false" href="#limiter" data-toggle="collapse" id="limiter_by_main"  class="overwrite-limiter">12 items/page</div>
                                                                <ul class="limiter collapse" id="limiter">
                                                                    <li> <a class="" href="javascript:void(0);"  data-value="12">12</a> </li>
                                                                    <li> <a class="" href="javascript:void(0);" data-value="24">24</a> </li>
                                                                    <li> <a class="" href="javascript:void(0);" data-value="36">36</a> </li>
                                                                </ul>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-lg-3">
                                                <div class="pager"> </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <?php
                        }
						if(!empty($comingsoonArys) && in_array($maincat_id, $comingsoonArys))
						{
						?>
<div style="position: relative;" class="myshoppage">
<div style="text-align: center; display: block; opacity: 1; transition: opacity 0.5s linear 0s; position: relative; height: 450px;" class="loader-opacity-div-1"> 
<span style="text-align: center; color: rgb(255, 255, 255); font-size: 32px; left: 40%; margin-top: 20%; position: absolute;">Coming Soon...</span> 
</div>
</div>
						<?php
						}
						else
						{
                        if (count($allowedProducts) == 0):
                            ?>
                            <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
                        <?php else: ?>
                            
                            <div class="content content-ring-diamonds" style="height: auto<?php //echo $products->count() == 12 ? '1510px' : 'auto';         ?>; overflow: hidden; position: relative; z-index: 0;">
							<div class="loader-opacity-div loader-diamonds-results" style="position: absolute;">
<img style="left: 50%; top: 20%; position: absolute;" src="<?PHP echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/base/default/packer/images/michael.gif" />
</div>
                                <ul class="products-grid itemgrid itemgrid-adaptive products-itemgrid-<?php echo $_columnCount; ?>col show-grid">
                                    <?php
                                    $parentli = '1';
                                    $parentliii = '1';
                                    foreach ($allowedProducts as $product) {
                                        switch ($parentliii) {
                                            case 1:
                                                $mainclassli = 'first';
                                                $parentliii++;
                                                break;
                                            case 2:
                                                $mainclassli = '';
                                                $parentliii++;
                                                break;
                                            case 3:
                                                $mainclassli = 'last';
                                                $parentliii = 1;
                                                break;
                                        }
                                        ?>
                                        <?php
                                        $simpleProductId = $product->getId();
                                        $remark_val = $product->getResource()->getAttribute('remark_val')->getFrontend()->getValue($product);
                                        $band_width = $product->getResource()->getAttribute('band_width')->getFrontend()->getValue($product);

                                        $_subproductids = Mage::getModel('catalog/category')->load($maincat_id)
                                                ->getProductCollection()
                                                ->addAttributeToSelect('*')                                                
                                                ->addAttributeToSort('remark_val', 'asc');
                                        $_subproductids->addAttributeToFilter('entity_id', array('neq' => $simpleProductId));
                                        $_subproductids->addAttributeToFilter('remark_val', array('eq' => $remark_val));
                                       
$EarringsTypes = explode(",", $product->getEarringsTypes());
//echo "<pre>";
//print_r($EarringsTypes);



                                        $product_name = $product->getName();
                                        $product_url = $product->getProductUrl();
                                        $product_image = (string) Mage::helper('catalog/image')->init($product, 'thumbnail');
                                        ?>
                                        <li class="itemwedding hover-effect <?php echo $mainclassli; ?> img-product-img-<?php echo $simpleProductId; ?>" style="min-height:395px;">
                                            <div class="product-action">

                                                <a href="<?php echo $product_url; ?>" title="<?php echo $product_name; ?>" class="product-image"> 
                                                    <img id="product-collection-image-<?php echo $product->getId(); ?>" data-srcx2="<?php echo Mage::helper('catalog/image')->init($product, 'thumbnail'); ?>" src="<?php echo Mage::helper('catalog/image')->init($product, 'thumbnail')->keepAspectRatio(true)->resize('270', '270'); ?>?sidebar=true" class="img-responsive lazy" alt="<?php echo $product_name; ?>" style="display: block;">
                                                </a>

                                                <div class="actions">
                                                    <div class="action-list quickview hidden-xs">
                                                        <div class="quickview-wrapper" onclick="quickview(this);" data-url="<?php echo Mage::getBaseUrl(); ?>ajaxproducts/index/quickview/product_id/<?php echo $product->getId(); ?>/"> <i class="fa fa-search-plus"></i> </div>
                                                    </div>
                                                    <div class="action-list">
                                                        <ul class="add-to-links">
                                                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                                                <li class="wishlist"><a href="<?php echo $this->helper('wishlist')->getAddUrl($product) ?>" class="link-wishlist bootstrap-tooltip" data-toggle="tooltip" data-placement="left" title="<?php echo $this->__('Wishlist'); ?>" data-original-title="Wishlist"><i class="fa fa-heart"></i></a></li>
                                                            <?php endif; ?>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="product-content">
                                                
												<h3 class="product-name">
												<a title="<?php echo $product_name; ?>" href="<?php echo $product_url; ?>">
												<?php echo Mage::helper('core/string')->truncate($product_name, 65); ?>
												</a>
												</h3>
												
                                                <div class="price-box">
                                                    <?php
                                                    $_currentCurrencyCode = Mage::app()->getStore()->getCurrentCurrencyCode();

                                                    $price = $product->getPrice();
                                                    if ($_currentCurrencyCode == 'USD') {
                                                        $price = Mage::helper('directory')->currencyConvert($price, 'SGD', 'USD');
                                                    }
                                                    ?>
                                                    <!--span class="regular-price" > 
                                                        <span data-price-val="<?php echo number_format($price, 2); ?>" class="price">
                                                            <?php echo Mage::helper('core')->currency($product->getPrice()); ?>
                                                        </span> 
                                                    </span--> 
													<?php echo $this->getPriceHtml($product, true) ?>
                                                </div>
                                            </div>
                                            
                                        </li>
                                        <?php
                                        $parentli++;
                                    }
                                    ?>
                                </ul>
                            </div>
                        <?php endif;
						}
						 ?>
                    </div>
                </div>
            </div>
            <div class="row show-grid">
                <div class="col-lg-12"></div>
            </div>
            <div class="row show-grid">
                <div class="col-lg-12">
                    <div class="site-postscript"></div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    min_price = <?php echo number_format($min_price, 0, '', ''); ?>;
    max_price = <?php echo number_format($max_price, 0, '', ''); ?>;
    jQuery(document).on('product-media-loaded', function () {
        ConfigurableMediaImages.init('small_image');
        jQuery(document).trigger('configurable-media-images-init', ConfigurableMediaImages);
    });
	
</script>
<script type="text/javascript">

	window.onload = function () { 
		if(jQuery('#styles_up').css('display') == 'block')
		{
		  jQuery(".nav-1 span.collapse").addClass('expand');
		  jQuery(".nav-1 span.collapse").removeClass('collapse');
		}
	}
			
    sourceArray = {
        sortby: 'Name',
        diraction: 'asc',
        limiter: '12',
        min_price: '0',
        max_price: '<?php echo number_format($max_price, 0, '', '');?>',
        price_from: '0',
        price_to: '<?php echo number_format($max_price, 0, '', '');?>',
        maincat: '<?php echo $maincat; ?>',
        maincat_id: '<?php echo $maincat_id; ?>',
        maincat_name: '<?php echo $maincat_name; ?>',
        style: [<?php
                        $styleAry = array();
                        foreach ($dataJewellSettingValues as $key => $value) {
                            $cmopare = false;
                            $value = str_replace(" ", "-", $value);
                            $styleAry[] = "'$value'";
                        }
                        echo implode(",", $styleAry);
                        ?>],
        colours: ['white-gold', 'rose-gold', 'yellow-gold'],
        metals: ['14k', '18k', 'platinum']

    };
    sourceArray.pages = '<?php echo $total_pages; ?>';
    sourceArray.page = '1';
    sourceArray.currSymbol = '<?php echo $currSymbol; ?>';
    var filterRingUrl = '<?php echo Mage::getBaseUrl() ?>diamonds/ajax/filterjewellerygiftringluxury';

</script>
<script src="<?php echo Mage::getBaseUrl(); ?>js/app/jewellerygiftluxuryunder150.js"></script>
