<?php
$selectedJewellerygiftMaincat = Mage::getSingleton('core/session')->getJewellerygiftMaincat();
$selectedJewellerygiftStyletype = Mage::getSingleton('core/session')->getJewellerygiftStyletype();

if ($_GET['maincat'] != '') {
    $maincat = $_GET['maincat'];
} else {
    $maincat = $selectedJewellerygiftMaincat;
}

if ($_GET['styletype'] != '') {
    $style = strtolower($_GET['styletype']);
} else {
    $style = $selectedJewellerygiftStyletype;
}

$dataJewellSettingValues = array();

if ($style == '') {
    Mage::app()->getFrontController()->getResponse()->setRedirect(Mage::getBaseUrl())->sendResponse();
    exit;
}

$dataSettingValues = $dataSettingValue;

$attributeStyleArys = array('White Gold', 'Yellow Gold', 'Rose Gold');
$attributeMetalArys = array('14k', '18k', 'Platinum');

//Load product model collecttion filtered by attribute set id Mage::getModel('catalog/category')->load(3)
if (isset($_GET['order'])) {
    $orderby = $_GET['order'];
} else {
    $orderby = 'name';
}
$products = Mage::getModel('catalog/category')->load(105)
        ->getProductCollection()
        ->addAttributeToSelect('*')
        ->setPageSize(12)
        ->addAttributeToSort($orderby, 'asc');

$collection = Mage::getModel('catalog/category')->load(105)
        ->getProductCollection()
        ->addAttributeToSelect('*')
        ->addAttributeToSort($orderby, 'asc');

//echo $collection->count();
$allowedProducts = array();

if ($dataJewellSettingValues != '') {
    foreach ($dataJewellSettingValues as $key => $styleVal) {
        if ($key != '') {
            $tempStyleArray[] = array('finset' => $key);
        }
    }
    $products->addAttributeToFilter($searchfor, $tempStyleArray);
    $collection->addAttributeToFilter($searchfor, $tempStyleArray);
}

/*$tempMetalsArrayb[] = array('finset' => '128');

$products->addAttributeToFilter('metals', $tempMetalsArrayb);
$collection->addAttributeToFilter('metals', $tempMetalsArrayb);*/

foreach ($products as $product) {
    if ($selectedDiamondType) {
        array_push($allowedProducts, $product);
    } else {
        array_push($allowedProducts, $product);
    }
}

// Getting product max and min prices
$all_prices = array();

foreach ($collection as $p) {
    array_push($all_prices, $p->getPrice());
}

$min_price = min($all_prices);
$max_price = max($all_prices);

$_currentCurrencyCode = Mage::app()->getStore()->getCurrentCurrencyCode();
if ($_currentCurrencyCode == 'USD') {
    $min_price = Mage::helper('directory')->currencyConvert($min_price, 'SGD', 'USD');
    $max_price = Mage::helper('directory')->currencyConvert($max_price, 'SGD', 'USD');
}

//$min_price--;
$min_price = '0';
$max_price++;
$maincat_id='105';
echo $this->getCurrentDirection();
$_category = Mage::getModel('catalog/category')->load($maincat_id);
$_imgHtml = '';
?>
<script type="text/javascript">
    window.ringFilterUrl = '<?php echo Mage::getBaseUrl(); ?>diamonds/ajax/filterjewellerygiftsale';
    window.ringTotalPages = '<?php echo $collection->count(); ?>';</script>
<style>
    .nav-1 .color-menu-thumb {
        max-height: 39px  !important;
        max-width: 35px  !important;
        margin-top: 0;
    }
    .filters-step-colours .filter li a.checked::after {
        background: #b0cde9 none repeat scroll 0 0;
        border-radius: 5px;
        color: #fff !important;
        content: " ";
        display: block;
        height: 29px;
        left: 20px;
        margin-top: 3px;
        position: absolute;
        top: 1px;
        width: 65%;
        z-index: -1;
    }
    .small-configurable > li {
        float: left;     
		text-align: center;  
    }
    .subspan {
        float: left;
        margin-top: -5px;
        position: relative;
        width: 100%;
		font-size: 11px;
        z-index: 999;
    }
    .sidebar-thumb-style {
        max-width: 40px;
        vertical-align: middle;
    }
    
    .category-products .products-grid .itemwedding .product-content {
            padding: 10px 0 !important;
        }
       
    .filters-step-2 .style li a.checked::after {
        background-image: radial-gradient(circle closest-side, #b0cde9, rgba(0, 0, 0, 0));
        content: " ";
        display: block;
        height: 33px;
        left: 29px;
        position: absolute;
        top: 1px;
        width: 33px;
        z-index: -1;
    }

</style>

<div class="main-wrapper">
    <div class="container">
        <div class="main">
            <div class="row show-grid">
                <div class="col-lg-12">
                    <div class="site-preface"></div>
                </div>
            </div>
            <div class="row show-grid">
                <div class="col-lg-12"></div>
            </div>
            <div class="row show-grid">
                <div class="col-lg-3 sidebar">
                    <div class="col-left">
                        <!-- Category Navigation BOF -->
                        <div class="block block-nav filters-step-2">
                            <div class="block-title"> <strong><span>Categories</span></strong> </div>
                            <div class="block-content">
                                <ul class="nav-accordion nav-categories" id="categories_nav" style="">
                                    
                                    <li class="level0 nav-1 level-top parent filters-step-colours"> <a class="level-top" href="javascript:;"><span>COLOURS</span></a>
                                        <ul class="level0 no-bullets filter colours" id="colours_list" data-filter="colours" style="display:<?php echo $selectedDiamondType == '' ? 'block' : 'none'; ?>">
                                            <?php
                                            foreach ($attributeStyleArys as $key => $value) {
                                                ?>
                                                <li class="level1 item nav-1-1 <?php if ($key == 0) { ?> first <?php } ?>"> 
                                                    <a  id="colours_list_<?php echo $key; ?>" class="checked" href="javascript:;"  data-value='<?php echo strtolower(str_replace(" ", "-", $value)); ?>' >
                                                        <img class="menu-thumb-small color-menu-thumb" src="<?php echo Mage::getBaseUrl(); ?>media/catalog/category/<?php echo strtolower(str_replace(" ", "-", $value)); ?>.png" alt=""> 
                                                        <span><?php echo ucwords($value); ?></span>
                                                    </a> 
                                                </li>
                                                <?php
                                            }
                                            ?>
                                        </ul>
                                    </li>
                                    <li class="level0 nav-1 level-top parent filters-step-metals"> <a class="level-top" href="javascript:;"><span>METALS</span></a>
                                        <ul class="level0 no-bullets filter metals" id="metals_list" data-filter="metals" style="display:<?php echo $selectedDiamondType == '' ? 'block' : 'none'; ?>">
                                            <?php
                                            foreach ($attributeMetalArys as $key => $value) {
                                                ?>
                                                <li class="level1 item nav-1-1 <?php if ($key == 0) { ?> first <?php } ?>"> 
                                                    <a  id="metals_list_<?php echo $key; ?>" class="checked" href="javascript:;"  data-value='<?php echo strtolower(str_replace(" ", "-", $value)); ?>' >
                                                        <span><?php echo ucwords($value); ?></span>
                                                    </a> 
                                                </li>
                                                <?php
                                            }
                                            ?>
                                        </ul>
                                    </li>
                                    <li class="level0 nav-1 level-top parent last"> <a class="level-top" href="javascript:;"><span>PRICES</span></a>
                                        <table class="prices-data" width="100%" style="margin-bottom: 17px;">
                                            <tr>
                                                <?php $currSymbol = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol(); ?>
                                                <td style="padding-left: 18px;"><span class="value-from"><?php echo $currSymbol . number_format($min_price); ?></span></td>
                                                <td align="right"><span class="value-to"><?php echo $currSymbol . number_format($max_price); ?></span></td>
                                            </tr>
                                        </table>
                                        <div class="rangeslider-s2 sidebar-price-slider" data-filter="price" data-min-value="" data-max-value="" data-min="" data-max=""></div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <!-- Category Navigation EOF -->
                        <div class="block block-list block-compare">
                            <div class="block-title"> <strong><span>Compare</span></strong> </div>
                            <div class="block-content">
                                <p class="empty">You have no items to compare.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="col-main category-products">

                        <?php
                        if ($_imgUrl = $_category->getImageUrl()) {
                            $_imgHtml = '<p class="category-image"><img class="img-responsive" src="' . $_imgUrl . '" alt="' . $this->escapeHtml($_category->getName()) . '" title="' . $this->escapeHtml($_category->getName()) . '" /></p>';
                        }
                        ?>
                        <?php if ($_imgUrl): ?>
                            <?php echo $_imgHtml ?>
                            <?php
                        endif;
                        if ($style != 'classic') {
                            ?>  
                            <div class="toolbar">
                                <div class="row">
                                    <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
                                        <div class="row">
                                            <div class="col-lg-9">
                                                <div class="sorter_wrap">
                                                    <div class="sort-by">
                                                        <div class="select-new">
                                                            <div class="select-inner"> <span>Sort by: </span>
                                                                <div aria-expanded="false" href="#sort_by" data-toggle="collapse" id="sort_by_main" role="button" class="overwrite-sortby">Name</div>
                                                                <ul class="sort_by in" id="sort_by" style="height: auto;">
                                                                    <li> <a href="&order=name" data-value="Name">Name</a> </li>
                                                                    <li> <a href="&order=style" data-value="Style">Style</a> </li>
                                                                    <li> <a href="&order=price" data-value="Price">Price</a> </li>
                                                                </ul>
                                                            </div>
                                                        </div>
                                                        <div class="direction-list"> 
                                                            <a title="Set Descending Direction" id="desc_by_dir" style="display: block;" data-dire="desc" href="&dir=desc" class="direction direction-up" style="line-height:1.8;">
                                                                <i class="fa fa-arrow-up"></i>
                                                            </a> 
                                                            <a title="Set Ascending Direction" id="asc_by_dir" style="display: none;"  data-dire="asc" href="&dir=asc" class="direction direction-down" style="line-height:1.8;">
                                                                <i class="fa fa-arrow-down"></i>
                                                            </a> 
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="limiter_wrap">
                                                    <div class="limiter">
                                                        <div class="select-new">
                                                            <div class="select-inner">
                                                                <div aria-expanded="false" href="#limiter" data-toggle="collapse" id="limiter_by_main"  class="overwrite-limiter">12 items/page</div>
                                                                <ul class="limiter collapse" id="limiter">
                                                                    <li> <a class="" href="javascript:void(0);"  data-value="12">12</a> </li>
                                                                    <li> <a class="" href="javascript:void(0);" data-value="24">24</a> </li>
                                                                    <li> <a class="" href="javascript:void(0);" data-value="36">36</a> </li>
                                                                </ul>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-lg-3">
                                                <div class="pager"> </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <?php
                        }
                        if (count($allowedProducts) == 0):
                            ?>
                            <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
                        <?php else: ?>
                            
                            <div class="content content-ring-diamonds" style="height: auto<?php //echo $products->count() == 12 ? '1510px' : 'auto';         ?>; overflow: hidden; position: relative; z-index: 0;">
<div class="loader-opacity-div loader-diamonds-results" style="position: absolute;">
<img style="left: 50%; top: 20%; position: absolute;" src="<?PHP echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/base/default/packer/images/michael.gif" />
</div>
                                <ul class="products-grid itemgrid itemgrid-adaptive products-itemgrid-<?php echo $_columnCount; ?>col show-grid">
                                    <?php
                                    $parentli = '1';
                                    $parentliii = '1';
                                    foreach ($allowedProducts as $product) {
                                        switch ($parentliii) {
                                            case 1:
                                                $mainclassli = 'first';
                                                $parentliii++;
                                                break;
                                            case 2:
                                                $mainclassli = '';
                                                $parentliii++;
                                                break;
                                            case 3:
                                                $mainclassli = 'last';
                                                $parentliii = 1;
                                                break;
                                        }
                                        ?>
                                        <?php
                                        $simpleProductId = $product->getId();
                                        $remark_val = $product->getResource()->getAttribute('remark_val')->getFrontend()->getValue($product);
                                        $band_width = $product->getResource()->getAttribute('band_width')->getFrontend()->getValue($product);

										$EarringsTypes = explode(",", $product->getEarringsTypes());
										//echo "<pre>";
										//print_r($EarringsTypes);

                                        $product_name = $product->getName();
                                        $product_url = $product->getProductUrl();
                                        $product_image = (string) Mage::helper('catalog/image')->init($product, 'thumbnail');
                                        ?>
                                        <li class="itemwedding hover-effect <?php echo $mainclassli; ?> img-product-img-<?php echo $simpleProductId; ?>" style="height: 395px; padding-bottom: 120px !important;">
                                            <div class="product-action">

                                                <a href="<?php echo $product_url; ?>" title="<?php echo $product_name; ?>" class="product-image"> 
                                                    <img id="product-collection-image-<?php echo $product->getId(); ?>" data-srcx2="<?php echo Mage::helper('catalog/image')->init($product, 'thumbnail'); ?>" src="<?php echo Mage::helper('catalog/image')->init($product, 'thumbnail')->keepAspectRatio(true)->resize('270', '270'); ?>?sidebar=true" class="img-responsive lazy" alt="<?php echo $product_name; ?>" style="display: block;">
                                                </a>

                                                <div class="actions">
                                                    <div class="action-list quickview hidden-xs">
                                                        <div class="quickview-wrapper" onclick="quickview(this);" data-url="<?php echo Mage::getBaseUrl(); ?>ajaxproducts/index/quickview/product_id/<?php echo $product->getId(); ?>/"> <i class="fa fa-search-plus"></i> </div>
                                                    </div>
                                                    <div class="action-list">
                                                        <ul class="add-to-links">
                                                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                                                <li class="wishlist"><a href="<?php echo $this->helper('wishlist')->getAddUrl($product) ?>" class="link-wishlist bootstrap-tooltip" data-toggle="tooltip" data-placement="left" title="<?php echo $this->__('Wishlist'); ?>" data-original-title="Wishlist"><i class="fa fa-heart"></i></a></li>
                                                            <?php endif; ?>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="product-content">
                                                <h3 class="product-name">
												<a title="<?php echo $product_name; ?>" href="<?php echo $product_url; ?>">
												<?php echo Mage::helper('core/string')->truncate($product_name, 65); ?>
												</a>
												</h3>
												
                                                <div class="price-box">
                                                    <?php
                                                    $_currentCurrencyCode = Mage::app()->getStore()->getCurrentCurrencyCode();

                                                    $price = $product->getPrice();
                                                    if ($_currentCurrencyCode == 'USD') {
                                                        $price = Mage::helper('directory')->currencyConvert($price, 'SGD', 'USD');
                                                    }
                                                    ?>
                                                    <!--span class="regular-price" > 
                                                        <span data-price-val="<?php echo number_format($price, 2); ?>" class="price">
                                                            <?php echo Mage::helper('core')->currency($product->getPrice()); ?>
                                                        </span> 
                                                    </span--> 
													<?php echo $this->getPriceHtml($product, true) ?>
                                                </div>
                                            </div>
											<?php
		if (in_array('137', $EarringsTypes)) {

		$productss = Mage::getModel("catalog/product")->load($product->getId());
		if($productss->getData('has_options')) {
				?>
				<div class="main-configurable">
<ul class="small-configurable">
		<?php
		foreach ($productss->getOptions() as $o) {
		$optionType = $o->getType();        
		if ($optionType == 'drop_down') {
		$values = $o->getValues();
		foreach ($values as $v) {                
		//echo $product->getPrice()+$v->getPrice().'<br>';
		$Optionprice = $v->getPrice();
		if ($_currentCurrencyCode == 'USD') {
			$Optionprice =Mage::helper('directory')->currencyConvert($v->getPrice(), 'SGD', 'USD');
		}
		?>

<li class="product-img-<?php echo $simpleProductId; ?>" onmouseover="changedata(this);">
<span class="sub-regular-price" style="display:none;"><?php echo $currSymbol.number_format($price+$Optionprice, 2); ?></span>
<a class="product-sub-image" title="<?php echo $v->getTitle(); ?>" href="<?php echo $product_url; ?>?studselect=<?php echo $v->getId(); ?>"> 
<img style="display: block; width: 29px;" class="img-responsive lazy" src="<?php echo Mage::getUrl('media') .'wysiwyg/icotheme/'. str_replace(' ', '_', str_replace('/', '_', $v->getTitle())).'.png'; ?>" >
<span class="subspan">
<?php echo $v->getTitle(); ?> 
</span>
</a>
</li>

		<?php
		}
		}
		
		}
		?>
		</ul>
</div>
		<?php
		}
		
		}
		?>

                                        </li>
                                        <?php
                                        $parentli++;
                                    }
                                    ?>
                                </ul>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
            <div class="row show-grid">
                <div class="col-lg-12"></div>
            </div>
            <div class="row show-grid">
                <div class="col-lg-12">
                    <div class="site-postscript"></div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    min_price = <?php echo number_format($min_price, 0, '', ''); ?>;
    max_price = <?php echo number_format($max_price, 0, '', ''); ?>;
    jQuery(document).on('product-media-loaded', function () {
        ConfigurableMediaImages.init('small_image');
        jQuery(document).trigger('configurable-media-images-init', ConfigurableMediaImages);
    });
	
</script>
<script type="text/javascript">

	window.onload = function () { 
		if(jQuery('#colours_list').css('display') == 'block')
		{
		  jQuery(".nav-1 span.collapse").addClass('expand');
		  jQuery(".nav-1 span.collapse").removeClass('collapse');
		}
	}
			
    sourceArray = {
        sortby: 'Name',
        diraction: 'asc',
        limiter: '12',
        min_price: '0',
        max_price: '0',
        price_from: '0',
        price_to: '0',
        maincat: '<?php echo $maincat; ?>',
        maincat_id: '105',
        maincat_name: '<?php echo $maincat_name; ?>',
        colours: ['white-gold', 'rose-gold', 'yellow-gold'],
        metals: ['14k', '18k', 'platinum']

    };
    sourceArray.pages = '<?php echo $products->getLastPageNumber(); ?>';
    sourceArray.page = '1';
    sourceArray.currSymbol = '<?php echo $currSymbol; ?>';
    var filterRingUrl = '<?php echo Mage::getBaseUrl() ?>diamonds/ajax/filterjewellerygiftsale';

    function changedata(abcgd)
    {
        var imgUrl = jQuery(abcgd).find("img").attr('data-srcx2');
        var linkUrl = jQuery(abcgd).find("a").attr('href');
        var className = jQuery(abcgd).attr('class');
        var proName = jQuery(abcgd).find('.sub-regular-name').html();
        var proId = jQuery(abcgd).find('.sub-regular-id').html();
        var proPrice = jQuery(abcgd).find('.sub-regular-price').html();
        var quickviewurl = '<?php echo Mage::getBaseUrl(); ?>ajaxproducts/index/quickview/product_id/' + proId;

        jQuery(".img-" + className + " .product-image img").attr("src", imgUrl);
        jQuery(".img-" + className + " .product-image").attr("href", linkUrl);
        jQuery(".img-" + className + " .quickview-wrapper").attr("data-url", quickviewurl);
        jQuery(".img-" + className + " h3 .product-name").html('<a title="' + proName + '" href="' + linkUrl + '">' + proName + '</a>');
        jQuery(".img-" + className + " .price-box .regular-price .price").html(proPrice);
    }

</script>
<script src="<?php echo Mage::getBaseUrl(); ?>js/app/jewellerygiftsale.js"></script>
