<?php
/**
 * @copyright    Copyright (C) 2015 IcoTheme.com. All Rights Reserved.
 */
?>
<?php
$_item = $this->getItem();
$isVisibleProduct = $_item->getProduct()->isVisibleInSiteVisibility();
$canApplyMsrp = Mage::helper('catalog')->canApplyMsrp($_item->getProduct(), Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM);
$tempProdId = Mage::getModel('trd_diamond/diamondprod')->load(1);
$_productName = ($_item->getProduct()->getId() == $tempProdId->getProductId() ? $_item->getCustomProductName() : $this->getProductName());

$_currentCurrencyCode = Mage::app()->getStore()->getCurrentCurrencyCode();

$_product = Mage::getModel('catalog/product')->load($_item->getProduct()->getId());

$ids = $_product->getCategoryIds();
?>
<li class="item">
    <?php if ($this->hasProductUrl() && $_item->getProduct()->getId() != $tempProdId->getProductId()): ?>
        <a href="<?php echo $this->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getProduName()) ?>"
           class="product-image">
               <?php
               if (in_array('103', $ids)) {
                   $_images = $_product->getMediaGalleryImages();

                   if ($_images) {
                       $i = 0;
                       $_productImage = '';
                       foreach ($_images as $_image) {
                           ?>
                           <img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail', $_image->getFile())->resize(83, 83) ?>" alt="<?php echo  $this->htmlEscape($_image->getLabel()) ?>" title="<?php echo  $this->htmlEscape($_image->getLabel()) ?>" />
                           <?php
                           
                           if($i==1)
                           {
                               break;
                           }
                           $i++;
                       }
                   }
               } else {
                   $_productImage = ($_item->getProduct()->getId() == $tempProdId->getProductId() ? "/" . $_item->getCustomProductImage() : (string) $this->getProductThumbnail()->resize(83, 83)->setWatermarkSize('30x10'));
                   ?>
                   <img src="<?php echo $_productImage; ?>" alt="<?php echo $_productName; ?>"/>
                 <?php
               }
               ?>
            
        </a>
           <?php else: ?>
        <span class="product-image">
            <?php
               if (in_array('103', $ids)) {
                   $_images = $_product->getMediaGalleryImages();

                   if ($_images) {
                       $ii = 0;
                       $_productImage = '';
                       foreach ($_images as $_image) {
                           ?>
                           <img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail', $_image->getFile())->resize(83, 83) ?>" alt="<?php echo  $this->htmlEscape($_image->getLabel()) ?>" title="<?php echo  $this->htmlEscape($_image->getLabel()) ?>" />
                           <?php
                           
                           if($i==1)
                           {
                               break;
                           }
                           $i++;
                       }
                   }
               } else {
                   $_productImage = ($_item->getProduct()->getId() == $tempProdId->getProductId() ? "/" . $_item->getCustomProductImage() : (string) $this->getProductThumbnail()->resize(83, 83)->setWatermarkSize('30x10'));
                   ?>
                   <img src="<?php echo $_productImage; ?>" alt="<?php echo $_productName; ?>"/>
                 <?php
               }
               ?>
        </span>
<?php endif; ?>
    <div class="product-details row-fluid show-grid">
        <p class="product-name clearfix"><?php if ($this->hasProductUrl()): ?><a
                    href="<?php echo $this->getProductUrl() ?>"><?php endif; ?><?php echo $this->htmlEscape($_productName) ?><?php if ($this->hasProductUrl()): ?></a><?php endif; ?>
        </p>
        <p class="row-fluid show-grid">
            Quantity: <?php echo $_item->getQty(); ?>
        </p>
<?php /* <strong><?php echo $this->getQty() ?></strong> x */ ?>
        <div class="items clearfix">
        <?php if ($canApplyMsrp): ?>
                <span
                    class="map-cart-sidebar-item"><?php echo $this->__('See price before order confirmation.'); ?></span>
            <?php else: ?>
    <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                            <?php echo $this->__('Excl. Tax'); ?>:
                        <?php endif; ?>
                        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales')): ?>
                        <?php
                        $origPrice = $_item->getCalculationPrice() + $_item->getWeeeTaxAppliedAmount() + $_item->getWeeeTaxDisposition();
                        if ($_currentCurrencyCode == 'USD') {
                            $origPrice = number_format(Mage::helper('directory')->currencyConvert($origPrice, 'SGD', 'USD'), 2, '.', '');
                        }
                        ?>
                        <?php echo $this->helper('checkout')->formatPrice($origPrice); ?>
                    <?php else: ?>
                        <?php
                        $origPrice = $_item->getCalculationPrice();
                        if ($_currentCurrencyCode == 'USD') {
                            $origPrice = number_format(Mage::helper('directory')->currencyConvert($origPrice, 'SGD', 'USD'), 2, '.', '');
                        }
                        ?>
                        <?php echo $this->helper('checkout')->formatPrice($origPrice) ?>
                    <?php endif; ?>
                    <?php if (Mage::helper('weee')->getApplied($_item)): ?>
                        <br/>
                        <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales')): ?>
                            <small>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                    <span class="nobr"><?php echo $tax['title']; ?>
                                        : <?php echo Mage::helper('checkout')->formatPrice($tax['amount'], true, true); ?></span>
                                    <br/>
                <?php endforeach; ?>
                            </small>
                            <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
                                <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                <span class="nobr"><small><?php echo $tax['title']; ?>
                                        : <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'], true, true); ?></small></span>
                                <br/>
                <?php endforeach; ?>
            <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales')):
                ?>
                            <small>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                    <span class="nobr"><?php echo $tax['title']; ?>
                                        : <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'], true, true); ?></span>
                                    <br/>
                <?php endforeach; ?>
                            </small>
                            <?php endif; ?>
                            <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
                            <span class="nobr"><?php echo Mage::helper('weee')->__('Total'); ?>
                                :<br/> <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice() + $_item->getWeeeTaxAppliedAmount() + $_item->getWeeeTaxDisposition()); ?></span>
                        <?php endif; ?>
        <?php endif; ?>
                <?php endif; ?>

                <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <?php $_incl = $this->helper('checkout')->getPriceInclTax($_item); ?>
                    <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                        <br/><?php echo $this->__('Incl. Tax'); ?>:
                    <?php endif; ?>
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales')): ?>
                        <?php echo $this->helper('checkout')->formatPrice($_incl + $_item->getWeeeTaxAppliedAmount()); ?>
                    <?php else: ?>
                        <?php echo $this->helper('checkout')->formatPrice($_incl - $_item->getWeeeTaxDisposition()) ?>
                    <?php endif; ?>
                    <?php if (Mage::helper('weee')->getApplied($_item)): ?>
                        <br/>
                        <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales')): ?>
                            <small>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                    <span class="nobr"><?php echo $tax['title']; ?>
                                        : <?php echo Mage::helper('checkout')->formatPrice($tax['amount'], true, true); ?></span>
                                    <br/>
                <?php endforeach; ?>
                            </small>
                            <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
                                <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                <span class="nobr"><small><?php echo $tax['title']; ?>
                                        : <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'], true, true); ?></small></span>
                                <br/>
                <?php endforeach; ?>
            <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales')):
                ?>
                            <small>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                    <span class="nobr"><?php echo $tax['title']; ?>
                                        : <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'], true, true); ?></span>
                                    <br/>
                <?php endforeach; ?>
                            </small>
                            <?php endif; ?>
                            <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
                            <span class="nobr"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>
                                :<br/> <?php echo $this->helper('checkout')->formatPrice($_incl + $_item->getWeeeTaxAppliedAmount()); ?></span>
                        <?php endif; ?>
        <?php endif; ?>
                <?php endif; ?>
            </div>
            <div class="access clearfix">
                <a href="<?php echo $this->getDeleteUrl() ?>" title="<?php echo $this->__('Remove') ?>"
                   onclick="return confirm('<?php echo $this->__('Are you sure you would like to remove this item from the shopping cart?') ?>');"
                   class="btn-remove">
                    <i class="fa fa-trash"></i>
                </a>
    <?php if ($isVisibleProduct): ?>
    <?php endif ?>
            <?php endif; //Can apply MSRP   ?>
        </div>


<?php if ($_options = $this->getOptionList()): ?>
            <div class="truncated" style="display: none">
                <div class="truncated_full_value">
                    <dl class="item-options">
    <?php foreach ($_options as $_option) : ?>
                            <dt><?php echo $this->htmlEscape($_option['label']) ?><span> :</span></dt>
                            <dd>
                            <?php if (is_array($_option['value'])): ?>
            <?php echo nl2br(implode("\n", $_option['value'])) ?>
                                <?php else: ?>
                                    <?php echo $_option['value'] ?>
                                <?php endif; ?>
                            </dd>
                            <?php endforeach; ?>
                    </dl>
                </div>
                        <?php /* <a href="#" onclick="return false;" class="details"><?php echo $this->__('Details') ?></a> */ ?>
            </div>
            <?php endif; ?>
    </div>

        <?php
        $attributeSetName = Mage::getModel('eav/entity_attribute_set')->load($_item->getProduct()->getAttributeSetId())->getAttributeSetName();
        ?>
    <?php if ($attributeSetName == 'ring' && $_item->getImportxlsId()): ?>
        <?php $importXlsModel = Mage::getModel('trd_importxls/importxls')->load($_item->getImportxlsId()); ?>
        <div class="diamond-box">
            <p>Diamond <?php echo $importXlsModel->getDiamondsName(); ?></p>
        </div>
<?php endif; ?>
</li>
