<div class="content-header">
  <table cellspacing="0">
    <tr>
      <th> <h3> <?php echo $this->__("Men Ring Product Import") ?> </h3>
      </th>
    </tr>
  </table>
</div>
<div class="entry-edit">
	<?php $formurl = Mage::getUrl('adminhtml/productimport_menring/import'); ?>
  <form enctype="multipart/form-data" method="post" action="<?php echo $formurl; ?>" id="import_product_form">
    <?php echo $this->getBlockHtml('formkey')?>
    <div class="entry-edit-head">
      <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__("Upload XLSX, XLS, CSV files for import products") ?></h4>
      <div class="form-buttons"></div>
    </div>
    <div id="base_fieldset" class="fieldset ">
      <div class="hor-scroll">
        <table cellspacing="0" class="form-list" style="width:99%;">
          <tbody>
            <tr>
              <td class="label"><label for="import_file"><?php echo $this->__('Select File to Import') ?> <span class="required">*</span></label></td>
              <td class="value"><input type="file" class=" required-entry" title="Select File to Import" value="" name="import_file" id="import_file"></td>
              <td class="value"><p class="form-buttons">
                  <button style="" class="scalable save" type="submit" title="<?php echo $this->__('Import Data') ?>" id="upload_button"><span><span><span><?php echo $this->__('Import Data') ?></span></span></span></button>
                </p></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </form>
</div>
<?php /* leave it for further development ?>
            <td class="form-buttons">
            <?php echo $this->getBackButtonHtml() ?>
            <?php echo $this->getResetButtonHtml() ?>
            <?php echo $this->getDeleteButtonHtml() ?>
            <?php echo $this->getSaveButtonHtml() ?>
            <?php */?>
<?php //echo get_class($this)?>
<?php //echo $this->getHandleUpdates()?>
<?php //echo $this->getMessagesBlock()->getGroupedHtml() ?>
</div>