<?php
/**
 * @copyright   Copyright (C)2015 IcoTheme.com. All Rights Reserved.
 */
?>

<?php
$blog = $this->getBlog();
$id = $this->getConfig('id');
$scroll = $this->getConfig('scroll');
$title = $this->getConfig('widget_title');
$helper = Mage::helper('widgetblog');
$date = Mage::getModel('core/date');
?>

<link rel="stylesheet" href="js/TouchCarousel 1.2.2/touchcarousel/touchcarousel.css" />
<link rel="stylesheet" href="js/TouchCarousel 1.2.2/touchcarousel/grey-blue-skin/grey-blue-skin.css" />


<div class="blog-homepage <?php echo $this->getConfig('classes') ?>" id="<?php echo $id ?>">
    <?php if ($title): ?>
        <!-- <h3 class="title-widget"><span><?php echo $title ?></span></h3> -->
    <?php endif ?>

    <br>
    <br>
    
    <div class="container">
        <div class="row">
		
		    <div class="col-md-8">
                <h3 class="title-widget"><span> <span class="instagram_icon" ></span>@MICHAELTRIO</span></h3>
                <div id="carousel-image-and-text" class="touchcarousel grey-blue">       
                    <ul class="touchcarousel-container instagram">
                               
                    </ul> 
                </div>
                <!-- <div class="instagram"></div>  -->
            </div>
			
		    <div class="col-md-4">
             <h3 class="title-widget"><span>TESTIMONIAL</span></h3>
             <?php echo Mage::getSingleton('core/layout')->createBlock('testimonial/testimonial')->setTemplate('testimonial/testimonial_top.phtml')->toHtml(); ?>
            </div>
            
        </div>
    </div>

    <div class="<?php echo $scroll == 1 ? 'owl-carousel ' : '' ?>">


    <!-- <div class="blog item>">
        <div class="blog-item-wrapper">
            <img class="img-responsive lazyOwl" data-srcx2="media/wysiwyg/icotheme/blog1.jpg" src="media/wysiwyg/icotheme/blog1.jpg" style="display: block;">
            
            <div class="main_content">
                <h3><a href="blog/customizable-magento-theme/">Ultra customizable premium theme with bunch of features!</a></h3>
                <span class="content">Integer scelerisque diam vitae aliquam fringilla. In vitae eros ac libero mattis molestie nec ...                    </span>
                <div class="content-bottom">
                    <span class="midle_content">
                        <span class="date"><i class="fa fa-clock-o"></i> 2015/Mar/17</span>
                        <span class="comment"><i class="fa fa-comment"></i> 0</span>
                    </span>
                    <span class="readmore"><a href="blog/customizable-magento-theme/">Read More</a> </span>
                </div>
            </div>
        </div>
    </div> -->



        <!--    
        <?php foreach ($blog as $_item): ?>
            <div class="blog item>">
                <div class="blog-item-wrapper">
                    <?php $img = $helper->getImgBlog($_item->getShortContent()); ?>
                    <?php if ($img): ?>
                        <?php if ($scroll): ?>
                            <img class="img-responsive lazyOwl" data-srcX2="<?php echo $img; ?>" data-src="<?php echo $img; ?>" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>"/>
                        <?php else: ?>
                            <img class="img-responsive lazy" data-srcX2="<?php echo $img; ?>" data-src="<?php echo $img; ?>" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>"/>
                        <?php endif; ?>
                    <?php endif; ?>
                    <div class="main_content">
                        <h3><a href="<?php echo $_item->getAddress(); ?>"><?php echo $_item->getTitle(); ?></a></h3>
                    <span class="content">
                        <?php echo $_item->getPostContent(); ?>
                    </span>
                        <div class="content-bottom">
                        <span class="midle_content">
                            <span class="date"><i class="fa fa-clock-o"></i> <?php echo $date->date('Y/M/d', $_item->getCreatedTime()); ?></span>
                            <span class="comment"><i class="fa fa-comment"></i> <?php echo (int)$_item->getCommentCount() > 0 ? $_item->getCommentCount() : '0'; ?></span>
                        </span>
                            <span class="readmore"><a href="<?php echo $_item->getAddress(); ?>"><?php echo $this->__('Read More'); ?></a> </span>
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach ?>

        -->
    </div>


    <script src="js/TouchCarousel 1.2.2/touchcarousel/jquery.touchcarousel-1.2.min.js"></script> 

    <script type="text/javascript">
        jQuery(document).ready(function(){
            // widgetConfig.init('<?php echo $id ?>', {
            //     carousel: <?php echo $this->getConfig('carousel') ?>
            // });
        });

        var dataG;

        jQuery( document ).ready(function( $ ) {

            
        });

            jQuery.ajax({
                type: "GET",
                url: "js/get_trio.php",
                dataType: "JSON",
                success: function(data){
                    dataG = data;

                    var i = 0;
                    var appendContent = '';

                    data.each(function(entry){
                        if(i<100){
                            appendContent += '<li class="touchcarousel-item"> <a target="_blank" class="item-block" href="https://instagram.com/michaeltrio/"> <img class="insta-img" src=' + entry + ' /> </a> </li>';
                        }
                        i++;
                    });

                    jQuery('.instagram').append(appendContent);

                    jQuery('.insta-img').on('load',function(){
                        jQuery('.instagram').fadeIn(700);
                    });

                    jQuery("#carousel-image-and-text").touchCarousel({                   
                        pagingNav: false,
                        snapToItems: false,
                        itemsPerMove: 4,                
                        scrollToLast: false,
                        loopItems: false,
                        scrollbar: true
                    });

                }
            });


        
    </script>

</div>
