<?php
/**
 * @copyright    Copyright (C) 2015 IcoTheme.com. All Rights Reserved.
 */
?>


<!-- Category Navigation BOF -->
<div class="block block-nav">
    <div class="block-title">
        <strong><span>Categories</span></strong>
    </div>
    <div class="block-content">
        
        <ul class="nav-accordion nav-categories" id="categories_nav" style="">
            
            <li class="level0 nav-1 level-top first parent">
                
                <a class="level-top " href="javascript:;"><span>STYLES</span></a> 

                <ul class="level0 no-bullets highlight-on" style="display: block;">
                    
                    <li class="level1 item nav-1-1 first ">
                    	<a href="javascript:;"><img class="sidebar-thumb-style" src="<?php echo Mage::getBaseUrl(); ?>media/wysiwyg/icotheme/puro/menu/icons_egr/solitaire.png" alt=""> <span>Solitare</span></a>
                    </li>

                    <li class="level1 item nav-2-2  ">
                    	<a href="javascript:;"> <img class="sidebar-thumb-style" src="<?php echo Mage::getBaseUrl(); ?>media/wysiwyg/icotheme/puro/menu/icons_egr/pave.png" alt=""> <span>Pavé</span></a>
                    </li>

                    <li class="level1 item nav-2-3  ">
                    	<a href="javascript:;"> <img class="sidebar-thumb-style" src="<?php echo Mage::getBaseUrl(); ?>media/wysiwyg/icotheme/puro/menu/icons_egr/channel-set.png" alt=""> <span>Channel-set</span></a>
                    </li>

                    <li class="level1 item nav-2-3  ">
                    	<a href="javascript:;"> <img class="sidebar-thumb-style" src="<?php echo Mage::getBaseUrl(); ?>media/wysiwyg/icotheme/puro/menu/icons_egr/side-stone.png" alt=""> <span>Side-stone</span></a>
                    </li>

                    <li class="level1 item nav-2-3  ">
                    	<a href="javascript:;"> <img class="sidebar-thumb-style" src="<?php echo Mage::getBaseUrl(); ?>media/wysiwyg/icotheme/puro/menu/icons_egr/vintage.png" alt=""> <span>Vintage</span></a>
                    </li>

                    <li class="level1 item nav-2-3  ">
                    	<a href="javascript:;"> <img class="sidebar-thumb-style" src="<?php echo Mage::getBaseUrl(); ?>media/wysiwyg/icotheme/puro/menu/icons_egr/halo.png" alt=""> <span>Halo</span></a>
                    </li>
                    
                </ul>
            </li>

            <!-- <li class="level0 nav-1 level-top parent">
                
                <a class="level-top" href="javascript:;"><span>COLOURS</span></a> 

                <ul class="level0" style="display: none;">
                    
                    <li class="level1 item nav-1-1 first ">
                    	<a href="javascript:;"><span>White gold</span></a>
                    </li>

                    <li class="level1 item nav-2-2  ">
                    	<a href="javascript:;"><span>Rose gold</span></a>
                    </li>

                    <li class="level1 item nav-2-3  ">
                    	<a href="javascript:;"><span>Yellow gold</span></a>
                    </li>                                                
                </ul>
            </li> -->


            <!-- <li class="level0 nav-1 level-top parent">
                
                <a class="level-top" href="javascript:;"><span>METALS</span></a> 

                <ul class="level0" style="display: none;">
                    
                    <li class="level1 item nav-1-1 first ">
                    	<a href="javascript:;"><span>18K</span></a>
                    </li>

                    <li class="level1 item nav-2-2  ">
                    	<a href="javascript:;"><span>Platinum</span></a>
                    </li>
                    
                </ul>
            </li> -->

            <li class="level0 nav-1 level-top parent">
                
                <a class="level-top" href="javascript:;"><span>Can be set with</span></a> 

                <ul class="level0" style="display: none;">
                    
                    <li class="level1 item nav-1-1 first ">
                        <a href="javascript:;"><span>Round</span></a>
                    </li>

                    <li class="level1 item nav-1-2  ">
                        <a href="javascript:;"><span>Princess</span></a>
                    </li>

                    <li class="level1 item nav-1-3  ">
                        <a href="javascript:;"><span>Emerald</span></a>
                    </li>

                    <li class="level1 item  ">
                        <a href="javascript:;"><span>Heart</span></a>
                    </li>

                    <li class="  ">
                        <a href="javascript:;"><span>Pear</span></a>
                    </li>

                    <li class="">
                        <a href="javascript:;"><span>Cushion</span></a>
                    </li>

                    <li class="">
                        <a href="javascript:;"><span>Radiant</span></a>
                    </li>

                    <li class="">
                        <a href="javascript:;"><span>Oval</span></a>
                    </li>

                    <li class="">
                        <a href="javascript:;"><span>Asscher</span></a>
                    </li>

                    <li class="">
                        <a href="javascript:;"><span>Marquise</span></a>
                    </li>
                    
                </ul>
            </li>


            <li class="level0 nav-1 level-top parent last">
                
                <a class="level-top" href="javascript:;"><span>PRICES</span></a> 

                <ul class="level0" style="display: none;">
                    
                    <li class="level1 item nav-1-1 first ">
                    	<a href="javascript:;"><span>$0 - $500</span></a>
                    </li>

                    <li class="level1 item nav-2-2  ">
                    	<a href="javascript:;"><span>$500 - $5000</span></a>
                    </li>

                    <li class="level1 item nav-2-3  ">
                    	<a href="javascript:;"><span>$5000+</span></a>
                    </li>                                                
                </ul>
            </li>




        </ul>
    </div>

</div>
<!-- Category Navigation EOF -->